### ISSUE TITLE
Allow null value.

### ISSUE THREAD

**Issue by pheaver** [alecthomas/voluptuous#116]
It looks like there isn't an easy way to allow a key to be null/None without writing your own validator. For my specific use case, I'd like to allow null keys and treat them just like they did not exist.

**Comment by alecthomas** [comment]
You should be able to just use `None` as they key: `Schema({None: object})`. Feel free to reopen if this is not what you're referring to.

**Comment by pheaver** [comment]
Sorry, I was not clear. I meant that the value of that key is null. For example, if I have a key 'n' that must be int or null in JSON, so that either of these is valid:

```
{"x": 1}
{"x": null}
```

There isn't an easy way to define that schema.

**Comment by alecthomas** [comment]
Schema({str: Any(int, None)})

**Comment by pheaver** [comment]
Oh!
