### ISSUE TITLE
[feature] Add way to get type of schema member

### ISSUE THREAD

**Issue by sk-** [alecthomas/voluptuous#122]
`Schema` should have a way to introspect the types. Currently you can achieve this only if your schema rules are plain Python types. However, if you use `All`, then there is no clean way to access the type data.

The only way is to call `f.__closure__[1].cell_contents`.

My use case is that I have a decorator that automatically extract GET or POST params and validates them. The problem I'm facing is that I need to specify twice (once in the schema and once more in the decorator) those params that may be repeated.

**Comment by alecthomas** [comment]
This wouldn't be possible without a large amount of refactoring, and I don't think the use case is that common.

**Comment by alecthomas** [comment]
I don't think this will be implemented, but thanks for the report.
