### ISSUE TITLE
Support collections.abc.Mapping rather than dict

### ISSUE THREAD

**Issue by patrick-jones** [alecthomas/voluptuous#125]
Attempting to validate request parameters in aiohttp fails because `validate_dict` tests explicitly that `data` is a dict rather than any dict-like object. It would be better to rely on the `collections.abc.Mapping` (`collections.Mapping` prior to 3.3) ABC -- that would make it easy to use in many web frameworks that use dict-like data structures that are not, strictly speaking, `dict`s.

**Comment by alecthomas** [comment]
Seems like a good idea, I'd welcome a patch.

**Comment by alecthomas** [comment]
This has been implemented.
