### ISSUE TITLE
Ability to have recursive schema

### ISSUE THREAD

**Issue by jd** [alecthomas/voluptuous#128]
Today there's no easy syntax to have a recursive schema. The best way to do it is to have a wrapper like that:

```python
>>> import voluptuous
>>> def s2(v):
...     return s1(v)
...
>>> s1 = voluptuous.Schema({"abc": voluptuous.Any(s2, "def")})
>>> s1({"abc": {"abc": "def"}})
{'abc': {'abc': 'def'}}
```

**Comment by alecthomas** [comment]
It's not clear to me how that could be expressed any other way than something similar to what you have?

**Comment by jd** [comment]
It's not clear to me either, I didn't find any other elegant solution. But it'd be nice if someone did. :)

**Comment by harlowja** [comment]
So I tried the following (might be something I'm missing since it doesn't work, ha).

https://github.com/harlowja/voluptuous/commit/afeac7249ae801f6e685974110acc0e993071892

But that seems like it could be a way to do this...

**Comment by alecthomas** [comment]
I think the solution @jd came up with is fine.

**Comment by miso-belica** [comment]
@alecthomas Solution is good enough but It would be fine to have it in documentation somewhere for others. I can prepare PR if you are busy :)

**Comment by alecthomas** [comment]
That would be great, thanks!
