### ISSUE TITLE
Default for missing key and invalid data

### ISSUE THREAD

**Issue by ncknuna** [alecthomas/voluptuous#130]
Maybe I'm missing something obvious, but there doesn't seem to be a way to say "use this default value if they key is missing or if validation fails". Basically, I would like to do the functional equivalent of something like this, in some kind of prettier way:
```
{
    Optional('foobar', default='default'): Any(int, lambda v: 'default'),
}
```
(Where if 'foobar' is missing or is invalid (not an int), it should take the value 'default'.)

That could either be a different kwarg for Optional, like "fallback", or a different Marker entirely. That could look like:
```
{
    Optional('foobar', fallback='default'): int,
}
```

**Comment by alecthomas** [comment]
The case where it is missing is what the `default` keyword parameter already worked:

```python
>>> s = Schema({Optional('key', default='value'): str})
>>> s({})
    {'key': 'value'}
```

But I've added `SetTo(v)` to solve the other case:

```python
>>> s = Schema({Optional('key', default='value'): Or(str, SetTo('default'))})
>>> s({})
    {'key': 'value'}
>>> s({'key': 1})
    {'key': 'default'}
```

**Comment by ncknuna** [comment]
I think the main thing I want is some syntactic sugar when the "default" kwarg to "Optional" is the same as "SetTo" would be, so I wouldn't have to duplicate it. This would also have the nice side effect of removing the need for the "Or". No worries if this is too much of a pain to do, I just thought it would be nice :)
