### ISSUE TITLE
Ability to allow for different value types in schema

### ISSUE THREAD

**Issue by somada141** [alecthomas/voluptuous#132]
Hi there,

Is it possible to define multiple accepted types of value in the schema dictionary?

For example I might have a `filesize` as a key which will typically be an `int` but for large files it might be a `long` and the two aren't derived from one another so they won't match. Similar issues arise with `str` and `unicode` types

Thus, is it possible to define a portion of a schema with multiple accepted types, e.g., switch:

```
"size": int,
```

to something like 

```
"size": int or long,
```

**Comment by alecthomas** [comment]
Yes, use `"size": Any(int, long)` (also aliased as `Or` in the latest version (or master)).
