### ISSUE TITLE
Allow easy extension of a Schema

### ISSUE THREAD

**Issue by hoxu** [alecthomas/voluptuous#135]
Excuse me if this is somehow possible already, but consider the following code:

```
>>> base = Schema({'a': int})                                                                                          
>>> base.schema
{'a': <type 'int'>}
>>> tmp = base.schema.copy(); tmp.update({'b': str})
>>> extended = Schema(tmp)
>>> extended.schema
{'a': <type 'int'>, 'b': <type 'str'>}
```

But extending a Schema this way is really awful, partially due to python [not having a proper way to merge dicts](http://stackoverflow.com/questions/38987/how-can-i-merge-two-python-dictionaries-in-a-single-expression).

I would propose a syntax like this:

```
>>> base = Schema({'a': int}, required=True)
>>> extended = base.extend({'b': str})
>>> base.schema # original is kept intact
{'a': <type 'int'>}
>>> extended.schema
{'a': <type 'int'>, 'b': <type 'str'>}
>>> extended.required # inherits the required attribute as well
True
```

What are your thoughts on this? I need this to use voluptuous, so I could perhaps work on a PR.

**Comment by alecthomas** [comment]
I really like this idea. I'd be happy to merge it.

**Comment by hoxu** [comment]
I started working on this, the initial work is viewable here:

https://github.com/alecthomas/voluptuous/compare/master...hoxu:schema-extension?expand=1

However, there is only support for dicts, not direct literals/types/lists/funcs. Any thoughts on what should be done about those?

**Comment by alecthomas** [comment]
I think that's a reasonable expectation. Put a line in the docstring mentioning the constraint, and maybe add an assert if you're super paranoid, and that should be fine.

**Comment by hoxu** [comment]
Closing the issue, as the PR was merged.
