### ISSUE TITLE
Exclusive keys nested in a list do not fail with the right error message

### ISSUE THREAD

**Issue by 2rs2ts** [alecthomas/voluptuous#143]
```python
from voluptuous import *

schema = Schema({
    'foo': [
        {
            Exclusive('bar', 'excl'): int,
            Exclusive('baz', 'excl'): int,
        }
    ],
})

data = {'foo':[{'bar':1,'baz':2}]}

print schema(data)
```

Output:

```
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    print schema(data)
  File "/home/me/test/.env/local/lib/python2.7/site-packages/voluptuous.py", line 333, in __call__
    return self._compiled([], data)
  File "/home/me/test/.env/local/lib/python2.7/site-packages/voluptuous.py", line 631, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/me/test/.env/local/lib/python2.7/site-packages/voluptuous.py", line 467, in validate_mapping
    raise MultipleInvalid(errors)
voluptuous.MultipleInvalid: invalid list value @ data['foo'][0]
```

I would expect instead a message like this instead: `two or more values in the same group of exclusion 'excl'`.

We are using voluptuous 0.8.7.

**Comment by alecthomas** [comment]
Thanks for the report!

**Comment by 2rs2ts** [comment]
Wow, quick fix. By the way, this problem isn't exclusive to `Exclusive`. I just got it to happen by using `Any(basestring, Match(...), msg="...")` inside of the list. I don't know if your fix is separate from that.

**Comment by alecthomas** [comment]
Yes it is specific... validators need to explicitly extend the path in order for deeper errors to be reported. If they don't do that, the top error is reported. If you find any more add them here and I'll fix them up as I go.

**Comment by alecthomas** [comment]
Can you provide a full example of how Any is not working?

**Comment by 2rs2ts** [comment]
Sorry, I meant `All`, not `Any`.

```python
from voluptuous import *

schema = Schema({
    'foo': [
        {
            'bar': [All(basestring, Match(r'\w+/.+'))],
        }
    ]
})

data = {'foo':[{'bar':['world']}]}

print schema(data)
```

Results in `voluptuous.MultipleInvalid: invalid list value @ data['foo'][0]['bar'][0]`. If you remove the list around the `bar` dict then you get the right error message.
