### ISSUE TITLE
Way to print a schema

### ISSUE THREAD

**Issue by harlowja** [alecthomas/voluptuous#146]
When a schema is say defined on a class it can be quite useful to be able to show that schema when say sphinx is ran over the class.

This helps make the class self-documenting, for example:

https://review.openstack.org/#/c/277551/5/tooz/schema_utils.py

This small change makes the schema attached say on https://review.openstack.org/#/c/277551/5/tooz/drivers/memcached.py show up when sphinx generates docs for it, thus helping make it possible for someone looking at the sphinx docs to easily know what the schema actually is.

It'd be nice if there was ``__repr__ `` or similar that showed there valid values, there conversion functions and such when repr (or str?) is called on them.

**Comment by harlowja** [comment]
Another idea is to have some kind of sphinx plugin that can render schema object it encounters in a nice way, that might be (although I don't know if its possible)...

**Comment by alecthomas** [comment]
I agree that this would be nice, but it would actually be quite difficult with the way the code is structured. For example, a lot of the voluptuous constructs are simply functions; they would all have to be modified to support repr.

Alas, I don't think this is feasible.

**Comment by harlowja** [comment]
Something simple is @ http://docs-draft.openstack.org/51/277551/9/check/gate-tooz-docs/03507cd//doc/build/html/developers.html#tooz.drivers.zookeeper.KazooDriver.options_schema so its not impossible to make something somewhat human readable that describes a schema.

**Comment by alecthomas** [comment]
I didn't say it was impossible, just difficult. Where is the code that does that?

**Comment by harlowja** [comment]
Code @ https://review.openstack.org/#/c/277551/9/tooz/schema_utils.py

**Comment by alecthomas** [comment]
Right, so if you look at the Voluptuous source you'll notice that almost all the validators are wrapped functions. They would all have to be converted to classes. That is quite a lot of mechanical work, but if you want to send a PR that does this, I'd be happy to review it.

**Comment by harlowja** [comment]
Sure!

**Comment by harlowja** [comment]
PR @ https://github.com/alecthomas/voluptuous/pull/147
