### ISSUE TITLE
Make it possible to access schema sub-items by key even when they are Optional

### ISSUE THREAD

**Issue by thatneat** [alecthomas/voluptuous#148]
It would be nice to be able to access sub-schemas in a clean fashion even when they are wrapped in an `Optional()` call.

say I've got a schema like this:
```python
from voluptuous import Schema, Optional
full_schema = Schema(
    {
        'bar': Schema(...)
        Optional('foo'): Schema(...)
    },
    required=True
)
```
I can access the 'bar' sub-schema like so:
```python
bar_sub_schema = full_schema.schema['bar']
```
But there's no clean way to access the `'foo'` sub-schema if, say, I want to use it independently.
```python
foo_sub_schema = full_schema.schema['foo']  #  KeyError
foo_sub_schema = full_schema.schema[Optional('foo')]  #  also KeyError
```
It seems that the wrapping that `Optional()` makes it so that the item hash no longer matches.
Fixing this might be as simple as providing a reasonable `Optional.__hash__()` function.

**Comment by alecthomas** [comment]
Accessing the schema is not really supported, but if you do want to do this you probably want something like:

```python
OptFoo = Optional('foo')

from voluptuous import Schema, Optional
full_schema = Schema(
    {
        'bar': Schema(...)
        OptFoo: Schema(...)
    },
    required=True
)
full_schema.schema[OptFoo]
```

(I haven't tested that)
