### ISSUE TITLE
Empty list are allowed by default?

### ISSUE THREAD

**Issue by cafiah** [alecthomas/voluptuous#156]
With a list schema like:

    schema = [ 1, 2, 3 ]
    s = voluptuous.Schema(schema)
    s([])

s([]) is valid but is as no value at all, how can i force list to have at least one on the values?

Thank's a lot, it's a nice project.

**Comment by cafiah** [comment]
well, it does work with All method like :
```
def validate_not_empty_list(value):
    if not value:
        raise voluptuous.Invalid("Should not be an empty list")
    return value

schema = voluptuous.All(validate_not_empty_list, [ 1, 2, 3 ])
s = voluptuous.Schema(schema)
s([])
```

**Comment by alecthomas** [comment]
You want:

```python
s = Schema(All([], Length(min=1)))
```
