### ISSUE TITLE
Validation errors nested in lists are broken and raise AttributeError

### ISSUE THREAD

**Issue by deuxpi** [alecthomas/voluptuous#157]
Between 0.8.9 and 0.8.10, it is no longer possible to correctly validate the content of lists. It seems that before the latest commits the inner exceptions were wrapped into a specific exception type, but now they may be propagated as MultipleInvalid exceptions. This exception type will not allow setting its `path` property, so it may cause the following error:

```python
>>> from voluptuous import *
>>> s = Schema(All([Any('one', 'two', 'three')]), Length(min=1))
>>> s(['one'])
['one']
>>> s(['four'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/local/lib/python2.7/site-packages/voluptuous.py", line 351, in __call__
    return self._compiled([], data)
  File "venv/local/lib/python2.7/site-packages/voluptuous.py", line 793, in validate_callable
    error.path = path + error.path
AttributeError: can't set attribute
```

If I run from 32aeeec65d77940655a2905c9f15114586eb785e I get the correct:

```python
>>> s(['four'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/local/lib/python2.7/site-packages/voluptuous.py", line 355, in __call__
    return self._compiled([], data)
  File "venv/local/lib/python2.7/site-packages/voluptuous.py", line 794, in validate_callable
    return schema(data)
  File "venv/local/lib/python2.7/site-packages/voluptuous.py", line 1394, in __call__
    raise e if self.msg is None else AllInvalid(self.msg)
voluptuous.MultipleInvalid: invalid list value @ data[0]
```

**Comment by alecthomas** [comment]
It's not clear to me why that attribute couldn't be set, so I just inserted the errors into the list instead. Quite odd. Anyway, let me know if that works or doesn't, and I'll push a new release.

**Comment by deuxpi** [comment]
Looks good to me! We're not in a rush to have a new version because we had to push current releases with a freeze on 0.8.9, so we'll just remove the freeze whenever a new version appears.

Thanks!

**Comment by balloob** [comment]
Yep, this fix fixes it for me too!

**Comment by cjw296** [comment]
See #158: Where .errors contained MultipleInvalidExceptions, .path is a property so can't be set.

I believe this surfaced when I stopped the loss of errors raised when multiple validators were used to validate an element in a sequence.

I think my fix is correct, hopefully @alecthomas can confirm.

**Comment by cjw296** [comment]
As a bit of explanation for my approach: if we have  MultipleInvalidException, we should prepend to the paths of all the contained Invalid(s), but of course, MultipleInvalidExceptions can be nested, hence the recursive approach.
