### ISSUE TITLE
Adding additional Validators 

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#164]
Since this is a data validation library, I would like if there are few new fields for validation in there. Some of the fields which is quite useful these days can be: 

- Email
- ip_address
- mac_address
- uuid

We can essentially use the validators provided by [validators](https://github.com/kvesteri/validators), however that would cause external source dependency.

**Comment by alecthomas** [comment]
I have no problem adding additional validators but as you suggest, I'd rather not add dependencies.

**Comment by tusharmakkar08** [comment]
Hey @alecthomas, please open this issue so that anyone who wants to extend the validators can contribute by referring to this issue. 
Thanks.

**Comment by alecthomas** [comment]
It's easier to just create a PR.
