### ISSUE TITLE
Float int typecasting issue

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#165]
How exactly can one go on float-int supported as input for validation? Let's say I have the following YAML: 

>     - product:  "a"
>       rating: 3.5
>     - product: "b"
>       rating: 3

I tried making schema using both `int` and `float` corresponding to `rating` but they gave error. How to go on doing such type of validations, which require typecasting?

**Comment by alecthomas** [comment]
You either want Any(int, float) or Coerce(float)
