### ISSUE TITLE
Coerce raises AttributeError when passing an instance rather than a type

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#167]
The following raises `AttributeError: 'Parser' object has no attribute '__name__'`:

```python
from voluptuous import *

class Parser(object):
    def __init__(self, settings):
        pass
    
    def __call__(self, value):
        pass


account_settings = {}
Coerce(Parser(account_settings))('a')
```

This is adapted from a larger implementation that uses this approach: the object that coerces the value uses settings so the behaviour can vary. The exception happens at `self.type_name = type.__name__` within `Coerce`.

I can see `Coerce` was built for type objects (e.g., `Coerce(int)`) and perhaps it wasn't intended for use cases like this. It would be good to hear your thoughts and whether or not `voluptuous` should support use cases like this.

**Comment by alecthomas** [comment]
Yes, that is correct.

For this situation I think it is appropriate to create your own validator function like Coerce that supports your use case.
