### ISSUE TITLE
Optional not raise exceptions

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#174]
I think in some use-cases it would be good for the schema validation to return the validation errors, but without actually raising an exception.

So that the caller can actually handle it accordingly.
Is it possible to do that or would you be interested in adding this?

Thanks

**Comment by alecthomas** [comment]
What is the difference between handling the validation errors from an exception vs. handling them as a return value?

**Comment by AndreaCrotti** [comment]
Well in one case you have to fetch the field that failed from the exception message, in the other case it's just a data structure.

Something like for example:

    print(myschema({'q': 'one'}, raise=False))
    {'q': 'wrong type'}

**Comment by AndreaCrotti** [comment]
That's also by the way what django forms and other forms library do.
They would eventually raise exceptions but you can always access the errors instead, without having to catch anything.

**Comment by alecthomas** [comment]
You can extract multiple errors, including the path to the failing field, from `MultipleInvalid.errors`. Plus I'm not sure how this would work with mutations like `Coerce()`... you'd have to validate twice, once to check and once to coerce, or return a tuple.

Honestly, I don't see any significant advantage and it increases complexity.
