### ISSUE TITLE
Support providing a Schema for Extra values

### ISSUE THREAD

**Issue by thatneat** [alecthomas/voluptuous#176]
Currently the only options for extra values in a schema is to allow or remove them. It'd be nice to support schemas where you don't know what all the keys are going to be, but you still want to validate the extra values against some rules. Example:

```python
schema = Schema({
    2: 3,
    Extra: Schema({'quality': int})
})

# valid
schema({2: 3, 'foo': {'quality': 5}, 'bar': {'quality': 73})

# invalid
schema({2: 3, 'foo': {'quality': ['I am a banana!']})
```

**Comment by alecthomas** [comment]
Is the following not sufficient?

```python
schema = Schema({
  2: 3,
  basestring: {'quality': int},
})
```

You could also replace `basestring` with `object` if you want to accept any key type.

**Comment by thatneat** [comment]
ah, yep. that totally covers it. Thanks!
