### ISSUE TITLE
Voluptuous Project Page

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#179]
I was thinking that maybe we can have a project page associated with `Voluptuous` using `gh-pages`. By doing that we would also be able to host the sphinx docs and link it there. 
@alecthomas : Let me know what you think about this.

**Comment by alecthomas** [comment]
👍

**Comment by tusharmakkar08** [comment]
Done http://alecthomas.github.io/voluptuous

**Comment by tusharmakkar08** [comment]
@alecthomas : I am also planning to remove `docs` folder from `master` and have it only in `gh-pages`. Let me know if that's fine with you.
