### ISSUE TITLE
Generate test data

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#183]
There are tools like this:
https://github.com/joke2k/faker

that allow you to generate some nice realistic input data.
I wonder if it would be easy to integrate the two to just be able to generate the fake data from the schema definition?

Well I suppose we still have to declare what is what for some more specialising factories (like address/name and so on and so forth) but what can be done with types could be done easily maybe?

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti, How would generating fake data from the schema definition help?

**Comment by alecthomas** [comment]
No response, closing.
