### ISSUE TITLE
tests missing from tarball

### ISSUE THREAD

**Issue by dhduvall** [alecthomas/voluptuous#188]
Part of the validation routine we (Oracle Solaris) do as part of building a component is to run any tests that come with it.  Since we build from released tarballs, we depend on what's there, and the voluptuous tarball (at least the 0.9.1 tarball on pypi) doesn't contain the tests.  I'm not sure why, though, since "setup.py sdist" puts the tests into the tarball.

**Comment by warsaw** [comment]
In Debian, we also want the tarball to contain the tests directory so that we can build from the PyPI release and run the tests at build time.

**Comment by alecthomas** [comment]
Done, and uploaded 0.9.3.

**Comment by warsaw** [comment]
@alecthomas Thanks!  One other change I found I had to make was to setup.py:

```
diff --git a/setup.py b/setup.py
index 6140253..4d6275d 100644
--- a/setup.py
+++ b/setup.py
@@ -32,7 +32,7 @@ setup(
     long_description=long_description,
     license='BSD',
     platforms=['any'],
-    packages=['voluptuous'],
+    packages=['voluptuous', 'voluptuous.tests'],
     author='Alec Thomas',
     author_email='alec@swapoff.org',
     classifiers=[
```

Without this, `voluptuous/tests/` doesn't get installed so when nose gets run during the Debian package build, none of the tests are found.
