### ISSUE TITLE
Problems installing voluptuous

### ISSUE THREAD

**Issue by balloob** [alecthomas/voluptuous#189]
At [Home Assistant](https://github.com/home-assistant/home-assistant) we use voluptuous and it is awesome. Thanks for all the work on this.

We've just released a new version which included an upgraded voluptuous. We went from 0.8.9 to 0.9.1.

We've had several users report that their installation of Home Assistant is hanging at the installation of voluptuous. The issue started with 0.9.0. I don't have a repo of the problem but we did find a workaround: installing `flake8` before installing `voluptuous` makes the problem disappear. 

Looking at the diffs between those versions, [these lines in setup.py](https://github.com/alecthomas/voluptuous/blob/master/setup.py#L54-L56) are probably the culprit:

```python
    setup_requires=[
        'flake8',
    ]
```

I did not want to submit a PR removing these lines without knowing the reasoning behind it. It looks to me that the lines can be removed because `tox` [is setup](https://github.com/alecthomas/voluptuous/blob/master/tox.ini#L24) to install the dependency.

**Comment by alecthomas** [comment]
Yeah I think that's fine to remove. If you could send me a PR removing that line it would be helpful, as I'm out and about at the moment.

**Comment by alecthomas** [comment]
Thanks for that! I've pushed 0.9.2 up to PyPi.

**Comment by balloob** [comment]
Thanks!
