### ISSUE TITLE
[] should evaluate to an empty list, not any list

### ISSUE THREAD

**Issue by tuukkamustonen** [alecthomas/voluptuous#198]
```python
>>> from voluptuous import Schema
>>> Schema({})({})
{}
>>> Schema({})({'foo': 1})
Traceback (most recent call last):
...
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['foo']
>>> Schema(int)(5)
5
>>> Schema(2)(5)
Traceback (most recent call last):
...
voluptuous.error.MultipleInvalid: not a valid value
>>> Schema([])([])
[]
>>> Schema([])([1])  # shouldn't this throw error?
[1]
```

Wouldn't it be logical to evaluate `list` for any list and `[]` for an exact value (an empty list)?

**Comment by tusharmakkar08** [comment]
I also agree with you here. One problem which I could think is the backward compatibility loss in here. 
@alecthomas What do you think ?

**Comment by alecthomas** [comment]
Yes, agreed. I don't think there is a significant issue with backwards compatibility, as even following the description of how `[...]` works you would expect this to be the case. That is, I think relying on `[]` to allow arbitrary list values is relying on undefined behaviour.

**Comment by tusharmakkar08** [comment]
@tuukkamustonen : Please submit the PR for the same. If you need any help, reach out to us.

**Comment by tuukkamustonen** [comment]
Should we also change `{}` to evaluate as is (an empty dict) always (even with `extra=True`)?

If one wants to define a free-form dict:

- With `extra=False`, he needs to use `dict` anyway.
- With `extra=True`, he can use `dict` instead of `{}`.

`{...}` would still be evaluated as nested schema.

That would break backwards-compatibility but would maybe make logic even more coherent (classes evaluated as types, instances evaluated as exact).

What do you think?

**Comment by tuukkamustonen** [comment]
Ping @alecthomas @tusharmakkar08

**Comment by tusharmakkar08** [comment]
Agree on this. It would make voluptuous more consistent.

**Comment by tusharmakkar08** [comment]
@tuukkamustonen : Are you working on PR for this issue?

**Comment by tuukkamustonen** [comment]
@tusharmakkar08: Not yet, but I'll take a look at it today...
