### ISSUE TITLE
Required('field', default=<value>): Any(bool, None) behaves differently for value = True/False

### ISSUE THREAD

**Issue by pavel-shpilev** [alecthomas/voluptuous#203]
Hi

Here's my schema and a test case for it:

```
import unittest

from voluptuous import Schema, Required, Any, MultipleInvalid


schema = Schema({
    Required('inview', default=False): Any(bool, None),
    Required('mute', default=True): Any(bool, None),
})


class TestSchemaValidation(unittest.TestCase):

    def setUp(self):
        self.data = {
            'inview': True,
            'mute': False
        }

    def _assertExceptionHasText(self, text):
        try:
            schema(self.data)
            raise AssertionError('MultipleInvalid not raised')
        except MultipleInvalid as e:
            self.assertIn(text, str(e))

    def test_inview(self):
        # Test knows how to deal with None and has default value.
        self.data['inview'] = None
        self.assertFalse(schema(self.data)['inview'])
        del self.data['inview']
        self.assertFalse(schema(self.data)['inview'])

    def test_mute(self):
        # Test knows how to deal with None and has default value.
        self.data['mute'] = None
        self.assertTrue(schema(self.data)['mute'])
        del self.data['mute']
        self.assertTrue(schema(self.data)['mute'])


if __name__ == '__main__':
    unittest.main()

```

I might be doing something wrong here (like allowing bool field to be None), but either way the behaviour is inconsistent depending on whether the field is True or False

**Comment by tusharmakkar08** [comment]
Hey @pavel-shpilev 

Can you please explain what the test is trying to achieve? From what I have understood, you are confusing `None` with `False` and hence the following code is working fine: 

    import unittest

    from voluptuous import Schema, Required, Any, MultipleInvalid


    schema = Schema({
    Required('inview', default=False): Any(bool, None),
    Required('mute', default=True): Any(bool, None),
    })


    class TestSchemaValidation(unittest.TestCase):
 
        def setUp(self):
            self.data = {
            'inview': True,
            'mute': False
        }

        def _assertExceptionHasText(self, text):
            try:
                schema(self.data)
                raise AssertionError('MultipleInvalid not raised')
            except MultipleInvalid as e:
                self.assertIn(text, str(e))

        def test_inview(self):
            # Test knows how to deal with None and has default value.
            self.data['inview'] = None
            self.assertEqual(schema(self.data)['inview'], None)
            del self.data['inview']
            self.assertFalse(schema(self.data)['inview'])

        def test_mute(self):
            # Test knows how to deal with None and has default value.
            self.data['mute'] = None
            self.assertEqual(schema(self.data)['mute'], None)
            del self.data['mute']
            self.assertTrue(schema(self.data)['mute'])


     if __name__ == '__main__':
        unittest.main()

**Comment by pavel-shpilev** [comment]
Hey

Sorry, should've explained that better. What I am trying to achieve is boolean fields with defaults that can also accept None (because such is the nature of my data source). And if the value is None I want the fields to fallback to default.

Back to the code, I just realised that inconsistency was due to assertFalse(None) not raising an exception.

**Comment by tusharmakkar08** [comment]
👍
