### ISSUE TITLE
Equality between schemas

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#208]
I just noticed that this doesn't work as I thought it would:
```
In [20]: v = voluptuous.Schema({voluptuous.Required('a'): unicode})

In [21]: v1 = voluptuous.Schema({voluptuous.Required('a'): unicode})

In [22]: v == v1
Out[22]: False
```

is that desired or maybe just not implemented?
Thanks

**Comment by alecthomas** [comment]
Do you have a use case in mind?

**Comment by AndreaCrotti** [comment]
Well we are currently creating an intermediate format that we use to define the schema, and transforming it into the actual Voluptuous schema.

In the tests it would be quite handy if we could just do an

assert generated_schema = v.Schema({....

instead of doing some other thing (like mocking atm)

**Comment by tusharmakkar08** [comment]
Yeah, makes sense. I can work on it.

**Comment by AndreaCrotti** [comment]
That was quick thanks a lot!
