### ISSUE TITLE
Decorating functions

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#216]
What do you think about this decorator

https://gist.github.com/AndreaCrotti/3d6b69acc55b637d32865dbf2d7b1fd5

(of course it can be improved and polished a lot).

Is that something we could include into the library?

**Comment by tusharmakkar08** [comment]
It's similar to https://github.com/alecthomas/voluptuous/pull/185 . Please have a look

**Comment by AndreaCrotti** [comment]
Ah my bad sorry, there is no example about using that in the README though, that's why I didn't notice.. should we add one?

**Comment by tusharmakkar08** [comment]
@ngergo @AndreaCrotti 

Yeah definitely. It would be great if you can add it in README.md and also [host](http://alecthomas.github.io/voluptuous/) the same via the documentation through `gh-pages`.

**Comment by AndreaCrotti** [comment]
Yes ok sure, by the way any idea about when this new validate will be in the next stable release?
Thanks

**Comment by tusharmakkar08** [comment]
I will discuss with @alecthomas and let you know.

**Comment by ngergo** [comment]
Hey @tusharmakkar08, 

I'll schedule contributing some docs to the validator.

**Comment by tusharmakkar08** [comment]
Cool. Thanks @ngergo
