### ISSUE TITLE
Remove the u prefix of unicode strings on error output

### ISSUE THREAD

**Issue by jmwri** [alecthomas/voluptuous#218]
I use unicode everywhere within my project, and this affects the output of Voluptuous' exceptions.

`required key not provided @ data[u'site_user_id']`

Is it possible to remove the unicode prefix?

**Comment by tusharmakkar08** [comment]
Can you please share your schema? Since according to [this test](https://github.com/alecthomas/voluptuous/blob/master/voluptuous/tests/tests.py#L24), it shouldn't be there at the first place.

**Comment by jmwri** [comment]
Changing the test to the following is what I am doing:

`schema = Schema({Required(u'q'): 1})`

Notice the unicode dict key. From what I have seen it is best practice to ensure all strings are unicode strings, so I only use unicode literals in my project.

**Comment by tusharmakkar08** [comment]
Umm.. Ok. Can you create a PR corresponding to it? You will have to do modifications in `schema_builder.py` for supporting this feature.

**Comment by jmwri** [comment]
I will investigate and ask if I need any help. Thanks :)!

**Comment by jmwri** [comment]
Sorry @tusharmakkar08, would you be able to briefly explain the flow? I'm not really reading this too well.

**Comment by tusharmakkar08** [comment]
@jmwri : Ok.

Start from Line 147 where `Schema` class is defined which calls `_compile` in Line 219  and depending on the type of schema appropriate function is called. For your scenario, you can focus on `self._compile_dict` and `self. _compile_object`. These functions further call `self. _compile_mapping` at Line 239. Here we call as a closure `validate_mapping` in Line 262, where the final output is yielded. So you need to essentially make changes in `self._compile_mapping` function.

**Comment by jmwri** [comment]
@tusharmakkar08 I have made changes to account for unicode `Marker` keys and plain text keys too. Are there any other types of keys?
