### ISSUE TITLE
Pytest?

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#221]
I used to use nosetests as well in the past, but generally py.test got way better and it's actively maintained..

Here for example some slides about it:
http://mathieu.agopian.info/presentations/2015_06_djangocon_europe/

if you would be interested about that I can do the change..

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti 

I am not able to see any significant improvement of py.test over nosetests except it being better maintained. (Nosetests is stable since quite a long time now and is a bit performance efficient than py.tes)

Thanks

**Comment by tuukkamustonen** [comment]
@tusharmakkar08 Actually, I also feel pytest would be a smart move. It is more modern and flexible, and has more traction, and that contributes directly to many many things (in my case, it integrates to PyCharm way better than nose). Besides, replacing nose with pytest would be a very minor task.

**Comment by tusharmakkar08** [comment]
I have integrated nose with PyCharm. It works fine. 
If you guys feel that it would be a great addition, please go ahead 😄

**Comment by AndreaCrotti** [comment]
There are a lot more plugins and integrations actually..

Yes ok I don't mind doing that, just didn't want to do the work if it was not going to be merged anyway..

**Comment by tusharmakkar08** [comment]
Hey @alecthomas, What are your views on this?
