### ISSUE TITLE
Function as validator

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#226]
I actually found we had a bug in my code with a Date validator, which can be summarised as this:

```
In [63]: import voluptuous as V

In [64]: def Date(fmt='%Y-%m-%d'):
    ...:    return lambda v: datetime.strptime(v, fmt)
    ...: 

In [65]: V.Schema(Date)(11)
Out[65]: <function __main__.<lambda>>
```

So instead of calling Date I was just passing it.
Stupid mistake surely, but I wonder if voluptuos could at least warn about this.
Returning a function from the schema validation is normally not something that makes sense right?

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti 

Can you please submit a PR for fixing the bug in Date Validator? Also, what do you mean when you say Voluptuous should warn about returning a function.

Thanks

**Comment by AndreaCrotti** [comment]
Mmm sorry to clarify @tusharmakkar08 there is no real bug, copying the example from the Readme it's correct.

However currently if a validator returns another function it just "fails silently" in a way, and I don't think there is a valid use case for a validator that returns functions instead of values?

**Comment by tusharmakkar08** [comment]
Yeah currently there isn't any use case per se but I don't see this harming the integrity of Voluptuous in any way. (Maybe in future we add validations of functions as well 😉 ). Closing this for now.

**Comment by AndreaCrotti** [comment]
Uhm well there is harm, I'm sure I'm not the first or the last to do that
silly mistake, and this one got in production since there was no specific
test case.

I think every validator function should really have a very good reason to
not return something of the same type..
At least maybe an option disabled by default that checks the type?

**Comment by alecthomas** [comment]
Because the validator isn't called until runtime, there's no way to validate up front whether the schema is correct. We could in theory check every value returned to see if it is a function, but that would only occur at validation (run) time. I haven't checked but my intuition is that it would also be a very intrusive change.

**Comment by AndreaCrotti** [comment]
Uhm ok I see it's not so easy I'll see if I can come up with something anyway, thanks
