### ISSUE TITLE
More flexible schema definition

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#228]
We needed to be able to change schema depending on countries, and for example maybe sometimes we just want to change if a field is required or not.

The way generally you declare voluptuous schemas doesn't make it very easy, so we just did a small function to translate from our format to voluptuous format, and we can write things like:

    MY_SCHEMA = {
        'id': Field(required=True, type=unicode),
        'choice': Field(required=True, type=V.Any('main', 'secondary')),
        'subinfo': SubSchema(SUB_SCHEMA),
    }

it works quite well for us, if that's something that might be interesting to include in voluptuous let me know!

Thanks

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti 

Can you explain what does `Field` in the example mentioned above ? 

Thanks

**Comment by AndreaCrotti** [comment]
The Field is really nothing special, just this

```
Field = namedtuple('Field', ['required', 'type'])
SubSchema = namedtuple('SubSchema', ['required', 'include'])
```
The smart bit is just the translation between one format and the other, but it's also just something like this
```
def build_voluptuous_schema(conf):
    def _process(conf):
        if isinstance(conf, (list, tuple)):
            schema = [_process(c) for c in conf]
        else:
            schema = {}
            for field_name, field in conf.items():
                voluptuous_type = R if field.required else O
                if isinstance(field, SubSchema):
                    schema[voluptuous_type(field_name)] = _process(field.include)
                else:
                    schema[voluptuous_type(field_name)] = field.type
        return schema
```

I just think that in general the current way of declaring the schema is not declarative "enough", and it would make it a lot easy to manipulate with some simple changes...

**Comment by alecthomas** [comment]
Can you show an example of how this is useful? I'm not getting it at the moment.

**Comment by AndreaCrotti** [comment]
Something like this is already a good example


default.py:

    SCHEMA = {
        'a': Field(required=True, type=int),
    }


other_country.py:


    from default import SCHEMA as default_schema

    SCHEMA = copy(default_schema)
    SCHEMA['a'].required = False

can avoid redefining fields if all it changes is if it's required or not, and access them by name easily.

**Comment by tusharmakkar08** [comment]
Hmm.. This would actually be a clean way for modifying schemas. @alecthomas What do you think about this?

**Comment by alecthomas** [comment]
Correct me if I'm wrong, but your proposal is equivalent to:

```python
```

**Comment by alecthomas** [comment]
I think this is a fairly niche thing to include. Something simpler, but possibly more intuitive, might be to make Required and Optional tags hash to their underlying value. This would allow the key to be replaced intuitively:

```python
schema_def = {Required('a'): int}
overridden_schema_def = copy(schem_def)
overridden_schema_def['a'] = int
```

 In general, I'm hesitant to just keep adding more and more features as it increases the cognitive load to using Voluptuous. I think it's fine to say "Voluptuous does not support that".

**Comment by tusharmakkar08** [comment]
Cool. I am fine with that too. Hence closing this issue.

**Comment by AndreaCrotti** [comment]
Well I don't think it's about adding features, it's just about making things simpler..
@alecthomas voluptuous already supports extending a schema, but you have do some relatively complex logic to do achieve that, because you're working around a data structure that was not designed for that..

**Comment by alecthomas** [comment]
Of course it's a new feature; it's a new way of expressing schemas using a `Field()` type.
