### ISSUE TITLE
IsDir: If given a file, check that its directory exists

### ISSUE THREAD

**Issue by kamakazikamikaze** [alecthomas/voluptuous#229]
Hey, I'm really digging Voluptuous! I've been able to cut out a lot of lines when refactoring our checks for configuration files we read in, all because of your project. Thank you for putting the time and effort in to create this.

`IsDir`, `IsFile`, and `IsPath` are great for checking existing files and directories. What they cannot do is check the _directory_ if a file name is passed in. For example, pretend that a field allows the user to input the destination file name that they want output to go to. This could be a new file _or_ an existing one to append to. (Like a log file.) I don't necessarily need to check if the file exists, I just need to check if the directory it goes to exists.

To demonstrate:

```Python
input = {
    'outfile' : '/srv/cron/myapp/logs/myapp.log' # File doesn't exist
}

# The code we want to run. If the file doesn't exist already, it will be created
def writelog(input):
    with open(input['outfile'], 'a') as log:
        log.writelines(msg)

# ==== Voluptuous ====
# Can't use this. The file isn't a directory!
dirschema = Schema({
    Required('outfile', default='./myapp.log'): IsDir(),  
})
# This throws an Exception if 'myapp.log' hasn't been created yet
fileschema = Schema({
    Required('outfile', default='./myapp.log'): IsFile(), 
})
# Same behavior as both of the above
anyschema = Schema({
    Required('outfile', default='./myapp.log'): IsPath(),
})
````

To get around this, I have one of two options:
```Python
# Require the user to split it themselves
input = { 
    'filename' : 'myapp.log',
    'output dir': '/src/cron/myapp/logs'
}

# Or split it prior to checking with Voluptuous
input2 = {
    'outfile' : '/srv/cron/myapp/logs/myapp.log'
}

input2['filename'] = input2['outfile'].split('/')[-1]
input2['output dir'] = '/'.join(input2['outfile'].split('/')[0:-1])
```

The issue with these is that if we require specifying multiple files in different directories, I/they will have to split each and every one of them. The user isn't going to like this if there's three or four, plus my solution isn't going to be very pretty.

A possible (example) solution using Voluptuous would be to modify the `IsDir` function:

```Python
@message('not a directory', cls=DirInvalid)
@truth
def IsDir(v, filedir=False):
    """Verify the directory exists.

    >>> IsDir()('/')
    '/'
    >>> IsDir()('/tmp/foo.txt', True)
    '/tmp'
    >>> IsDir()('/fake/foo.txt', True)
    DirInvalid: not a directory

    :param filedir: If a file name is included, strip it out first
    """
    
    return os.path.isdir(v if not filedir else os.path.dirname(v))
```

Hopefully that all makes sense and demonstrates why it may be worthwhile to implement.

**Comment by tusharmakkar08** [comment]
Hey @kamakazikamikaze 

It feels good to hear that Voluptuous is helping you reducing the complexity of your codebase. 

Thanks for your feedback about `IsDir()`. However, I think it would be over-engineering to add `filedir`. I feel the correct way to do what you want to achieve would be something like: 

```
dirschema = Schema({
    Required('outfile', default=os.path.dirname(os.path.abspath('./myapp.log'))): IsDir(),  
})
```

Thanks.

**Comment by kamakazikamikaze** [comment]
Unfortunately this wouldn't resolve the issue. If someone wanted to have a new log file spawned at `/tmp/foobar.log`, `IsDir()` would throw an exception and this would just create a default one in the running directory.

I understand that it may be over-engineering. I'll just use a helper function when we need this specific behavior. Thanks for responding so soon!

**Comment by tusharmakkar08** [comment]
The `writelog` code which you mentioned, would also throw an error if the directory `/tmp` isn't present. Additionally, I haven't done anything extra than what you mentioned in your modified implementation of `IsDir()` (just moved the logic to the non-library side). 
Maybe I am missing some point here, please clarify it. 

Thanks.

**Comment by kamakazikamikaze** [comment]
Sorry, I get a little wordy when trying to explain things. The order of code also wasn't that great.

> The writelog code which you mentioned, would also throw an error if the directory `/tmp` isn't present. 

That's the error we want to prevent by implementing Voluptuous. We want to be able to check that, if given a file name, the destination/target directory it is located in exists. So if I'm given `'/tmp/foo.log'`, I want to check that `/tmp` is a valid directory. I can't pass this string (`'/tmp/foo.log'`) directly to `IsDir` because `foo.log` isn't a directory. I can't always use `IsFile` because if `foo.log` hasn't been created yet, it raises an exception.

For now I've decided to just use a lambda function to cut off the file name from the string and pass the result to `IsDir`, which works fine.
