### ISSUE TITLE
Validate a datetime.datetime instance?

### ISSUE THREAD

**Issue by nowox** [alecthomas/voluptuous#243]
When deserializing data using `pyyaml`/`ruamel.yaml` date are returned as a datetime instance. 

I did not find a native solution on voluptuous but I eventually wrote this: 

```
def IsDate(date):
    if isinstance(date, (datetime.datetime, datetime.date)):
        return date
    raise DateInvalid('value is not a valid date %s' % repr(date))
```

Would it be useful to elaborate and make a pull request?

**Comment by tusharmakkar08** [comment]
A [datetime class](http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html?highlight=datetime#voluptuous.validators.Datetime) has been added. It'll be pushed out in next release. A sample test can be found [here](http://alecthomas.github.io/voluptuous/docs/_build/html/_modules/voluptuous/tests/tests.html#test_datetime).

**Comment by nowox** [comment]
Hey @tusharmakkar08. I think you did not understand what I wanted to propose. The [datetime class](http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html?highlight=datetime#voluptuous.validators.Datetime) only accepts strings not datetime instances. It is not possible to do this: 

```
Schema(Datetime())(datetime.datetime.now)
```

**Comment by sfelf** [comment]
@nowox Is this what you are looking for?

```
>>> import datetime
>>> from voluptuous import Any, Schema
>>> s = Schema(Any(datetime.datetime, datetime.date))
>>> s(datetime.datetime.now())
datetime.datetime(2016, 11, 9, 23, 1, 3, 690357)
>>> s(datetime.date.today())
datetime.date(2016, 11, 9)
```

**Comment by nowox** [comment]
Damned... I feel I'm stupid. 

Thanks
