### ISSUE TITLE
Validating dictionary with unknown keys

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#244]
I had the situation a few time where I wanted to validate something like

```
    {'a': 1, 'b': 2}
```

where however the key values are arbitrary (even if always strings).
Is there a way to write a schema for such a thing?
The alternative could be to make a list of dictionaries of course like

```
    [{'key': 'a', 'value': 1}]
```
which is easy to deal with, but I wonder if I can avoid that..

**Comment by sfelf** [comment]
@AndreaCrotti Would this satisfy your use case?

```
>>> from voluptuous import Schema
>>> s = Schema({str: int})
>>> s({'a': 1, 'b': 2})
{'a': 1, 'b': 2}
```

**Comment by AndreaCrotti** [comment]
Ah cool yes I didn't know I could have a callable also as key, thanks @sfelf
