### ISSUE TITLE
Can voluptuous play well with pyparsing?

### ISSUE THREAD

**Issue by nowox** [alecthomas/voluptuous#246]
I am wondering how good it could be to have a native support for `pyparsing` in `voluptuous`. They are both some really powerful packages and I have the intuition they could play well together. 

Isn't that schema nice?

```
s = Schema( Suppress(':') + Word('abc') + Suppress(':') )
s(':aabbcc:')
aabbcc   
```

A first step could be easily achieved by making a pyparsing `ParserElement` callable and then retrieve its first element: 

```
class PyparsingInvalid(Invalid):
    pass

class Pyparsing(object):
    def __call__(self, value):
        try:
            return self.pyparsing_schema.parseString(value)[0]
        except ParseException as e:
            raise PyparsingInvalid(e.msg)
    def __init__(self, schema):
        self.pyparsing_schema = stringStart + schema + stringEnd
```

The minor difference with the initial idea is the need to explicitly cast a `ParseElement` to a `Schema`:
 
```
s = Schema( Pyparsing(Suppress(':') + Word('abc') + Suppress(':')) )
```

In order to enhance the synergy between `pyparsing` and `voluptuous` it would be good to make both packages *more* compatible. This could be done on both sides: 

1. pyparsing `ParseElement`

Making `__call__` not set the default result name, but instead call `parseString` which will result in an unwanted compatibility break. 

2. voluptuous

Detect if the input is a `pyparsing.ParserElement` and automatically wrap the `Pyparsing` class around it. 

```
try: 
    from pyparsing import ParserElement as _parserElement
except ImportError: 
    class _parserElement(): 
       pass
...

def wrap_pyparsing(element):
    if isinstance(element, _parseElement):
        return Pyparsing(element)
    return element
```

One last point to consider is to define what should `Pyparsing` return once called: 

1. An instance of `ParseResults` which should not be very useful in a voluptuous schema
2. The first element: `foo.parseString(bar)[0]`
3. A `list` or a `dict` with `list(foo.parseString(bar)[0])`
4. Something configurable by the user using either a `kwargs` or a global setting. 

Regarding this latter point, the most straightforward way to increase the synergy would be to keep the proposed `Pyparsing` and add to it the ability to choose what output the user wants: 

```
Schema(Pyparsing(Suppress(':') + Word('abc') + Suppress(':'), output=lambda x: x[0]))
```

Or...

```
Schema(All(
   Pyparsing(Suppress(':') + Word('abc') + Suppress(':')),
   lambda x: x[0]
))
```

Any better idea?

**Comment by alecthomas** [comment]
I've got to be honest; I don't think this is something voluptuous should include. If an adaptor layer would be useful it should be in a separate package, `voluptuous-pyparsing` for example.
