### ISSUE TITLE
Boolean should validate rather than coerce values

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#247]
This issue is about a design decision regarding `Boolean`.

The following schema:

```python
s = Any(Boolean(), None)
```

intends to express the idea of "any boolean value or `None`". This seems reasonable but for the value `None` it evaluates to `False`:

```python
>>> s(None)
False
```

This happens because `Boolean` coerces the value using `bool()` and therefore "validates" the value. Although it makes sense that `Any` checks the validators from left to right, this result can be an unexpected result if one has not read the docstring of `Boolean`. For the values `True` and `False` this schema also succeeds but it returns the values `True` and `False` as expected.

It seems that `Boolean` differs from other validation objects in the voluptuous library by doing  validation for string values but coercion for non-string values.

It would be more explicit to let users express coercion using `Coerce(bool)` and to implement `Boolean` as a validator:

```python
@message('expected boolean', cls=BooleanInvalid)
def Boolean2(v):
    if isinstance(v, basestring):
        v = v.lower()
        if v in ('1', 'true', 'yes', 'on', 'enable'):
            return True
        if v in ('0', 'false', 'no', 'off', 'disable'):
            return False
        raise ValueError
    if not isinstance(v, bool):
        raise ValueError
    return v
```

The schema mentioned earlier can be fixed by doing:

```python
s = Any(None, Boolean())
```

but it does mean that a new developer could add another component after `Boolean()` and introduce a bug.

**Comment by alecthomas** [comment]
The docs on Boolean are quite clear, and its purpose is intentional. Also, it's behaviour won't be changing now. 

What exactly are you trying to achieve? Switching the order in your Any will fix your particular issue...
