### ISSUE TITLE
Does Voluptuous support biconditionals across Nodes?

### ISSUE THREAD

**Issue by acouch00** [alecthomas/voluptuous#252]
I'm using voluptuous to do some server-side verification of incoming data on our service.  My code follows the form:
`
schema = Schema({Required('key'): str,
                                 ...})
`

Currently, I'm running into a situation where our API requires users to specify two particular keys simultaneously, or requires that they are omitted altogether.  

In other words, these two keys (or Nodes, in voluptuous parlance) are either simultaneously Required, or simultaneously not supposed to be specified.  Essentially, these two keys must behave as a biconditional.

Here's a quick truth table, for illustrating the necessary behavior:

Key 1|Key 2|is_valid?
-----|------|--------
1|1|1
1|0|0
0|1|0
0|0|1

Is there a provision in voluptuous that allows you to do something like this?  I can move this check outside the voluptuous validator code, but I thought I'd reach out and see if I've overlooked something.

Thanks in advance!

**Comment by EgoWumpus** [comment]
It is a bit awkward but you can supply two schemas, one with Required on both and one with neither appearing. Then you can just Either those two schemas. 

Hope this helps!
Nathaniel Ford

**Comment by sfelf** [comment]
Would Inclusive work for your use case?

`schema = Schema({Inclusive('key1', 'key1_key2'): str, Inclusive('key2', 'key1_key2'): str})`

**Comment by acouch00** [comment]
Ah, Inclusive seems to be exactly what I was looking for.

Thanks so much, everyone!
