### ISSUE TITLE
schema validation duplicates reference types (dictionaries/lists)

### ISSUE THREAD

**Issue by SimplyKnownAsG** [alecthomas/voluptuous#253]
I have a schema I am trying to validate which uses YAML's alias/anchor to prevent duplication of inputs. When trying to use `voluptuous` for validation on the YAML-parsed `dict`, it creates new instances for each alias. Can `voluptuous` be changed to understand visited items and not duplicate entries?

Example YAML (joke obviously):
```yaml
by month:
  November:
  - &mickey {birthday: '1928-11-18', name: Mickey}
by year:
  1928:
  - *mickey
````

Example test:

```python

import calendar
import datetime

def test_dict_reference():
    mouse = Schema({"name": str, "birthday": Date()})
    mice = Schema([mouse])
    schema = Schema({
        "by month": {In(set(calendar.month_name[1:])): mice},
        "by year": {Range(min=1900, max=datetime.datetime.now().year): mice}
    })
    mickey = dict(name="Mickey", birthday="1928-11-18")
    data = {"by month":
            {
                calendar.month_name[11]: [mickey]
            },
            "by year":
            {
                1928: [mickey],
            }
            }
    out = schema(data)
    orig = out['by month'][calendar.month_name[11]][0]
    dup = out['by year'][1928][0]
    assert orig is dup, 'they are not the same ({}) != ({})'.format(id(orig), id(dup))
```

**Comment by alecthomas** [comment]
This seems like a pretty niche requirement. Couldn't deduplication just occur after Voluptuous validates?

**Comment by SimplyKnownAsG** [comment]
I think de-duplicating after validation is more easily said than done. Specifically, object equivalence does not necessarily indicate they are the same object. One option would be to do "in place" validation rather than creating new objects, but I think that runs into a similar issue as proposed. 

I am also a bit surprised this has not come up given `voluptuous`' popularity, and the usage is quite possibly niche. However, I don't think references are that uncommon in Python (even if JSON doesn't support it).

**Comment by alecthomas** [comment]
I mentioned post-deduplication as an option, because it's not clear what the actual use-case for this is. I understand that you're taking a YAML file, parsing it, then validating it, but not *why* you care about the validated data maintaining references.

I think the fact that it hasn't come up before also indicates just how niche it is. Data being validated by voluptuous is generally just plain-old-data, so preserving references is not that useful.

**Comment by SimplyKnownAsG** [comment]
Understood, and, I think we agree: _you should prevent unnecessary requirements from becoming requirements_.

The actual use case is input for a composite pattern. The reason I care is because in our application we have three input mechanisms, 1) directly through YAML, 2) through a "UI" which can generate the YAML, and 3) programmatic generation. Effectively we validate input -> generate corresponding data structures -> allow user configuration, and -> dump back to YAML. Since the current implementation of `voluptuous` generates reference duplicates, the final dump to YAML can become quite large and unwieldy. As a result, we currently can't use some features from `voluptuous`, such as defaults.

**Comment by alecthomas** [comment]
While I appreciate your particular use-case, I don't think this is a problem that Voluptuous should be solving.

**Comment by SimplyKnownAsG** [comment]
@alecthomas, I understand and respect your decision. At the same time, I think that Voluptuous is a bit inconsistent in that if you intend for it to only support "data", which I take to mean basic data types such as strings and numbers, but :
* Voluptuous also supports some file system functions, which seem outside the traditional definition of "data".
* Voluptuous even goes further by supporting `Object`s as both input and output.
* Finally, Voluptuous has a fairly good understanding of Python's object model as demonstrated by support for `__slots__`.

All these considerations, to me, seem at odds with your current conclusion to not support object references. Beyond that, I think that refactoring the code to allow for a state more robust than `path = list()` (which is what is required to support the proposed requirement) could potentially alleviate what seem to me to be less than desirable features:
* Validator `callable` objects, such as `Schema`, `Msg`, and `Coerce`, have inconsistent signatures with the "compiled" functions generated in `schema_builder.py`
* `error.Invalid.prepend` is a bit odd in that the represented `path` is momentarily incorrect.
* (more-so than the others, this is a bit of a stretch) you could even use a state object `with` `__enter__` and `__exit__` to accumulate errors rather than stuffing them into a `list`.
