### ISSUE TITLE
Validation of a dictionary runs in O(n^2)

### ISSUE THREAD

**Issue by odedfos** [alecthomas/voluptuous#259]
Currently all keys in the dictionary are matched against all keys in the schema. If we have a large set of keys then the validation takes very long.

Here is a test that simulates the problem. A single validation should take under 1 ms but currently takes 12 ms.

```
def test_validation_performance():
    """
    Naive validation of a dictionary with many keys with a schema that has many keys
     This test verifies a single validation runs in under 1 msec
    :return:
    """
    number_if_keys_in_schema = 100
    iterations = 1000
    threshold_ms = 1

    schema_dict = {str(i): str for i in range(number_if_keys_in_schema)}

    schema = Schema(schema_dict)

    data = {str(i): str(i) for i in range(number_if_keys_in_schema)}

    start = time.time()

    for i in xrange(iterations):
        schema(data)

    total_elapsed = time.time() - start
    avg_per_round = round(total_elapsed * 1000 / iterations, 3)
    print("Total: %s secs, avg: %s ms" % (round(total_elapsed, 3), avg_per_round))

    assert avg_per_round < threshold_ms, "Avg validation %s > %s ms" % (avg_per_round, threshold_ms)
```

**Comment by odedfos** [comment]
Thanks!
When is a pypi release expected?

**Comment by tusharmakkar08** [comment]
Hey @odedfos 

We need to update `CHANGELOG.md` for the corresponding changes. Once it's done, we'll release it. Add your changes in the `CHANGELOG.md` and create a corresponding PR. We are planning to release new version in the early February. 

Thanks.

**Comment by odedfos** [comment]
@tusharmakkar08, Any update on the package release?
