### ISSUE TITLE
Schema contraction

### ISSUE THREAD

**Issue by mprager** [alecthomas/voluptuous#261]
There is a useful function in the Schema class that allows extension of a schema by adding keys to it. This saves a lot code when you have multiple schema with only minor variations. Something that might also be useful is the ability to contract a schema, taking keys away. I'm not sure if this would be too specific a feature for this library, and I'm also not sure of a clean way to do it, but right now we write our own helper functions to do just this.

Is it worth pursuing?

**Comment by tusharmakkar08** [comment]
Hey @mprager 
It's like an inversion of `extend`. Can you maybe give couple of examples where this can be useful? 
Thanks

**Comment by mprager** [comment]
yeah, so i was thinking of a scenario like the following:

```
v0 = {
"a": int,
"b": float,
"c": string
}

v1 = {
"a": int,
"b": float,
"c": string,
"d": int
}

v2 = {
"a": int,
"b": float,
"d": int
}
```

in a chain like this where schema build off of each other. v1 would be an extension of v0, and v2 would be an extension of v1 (removing the key). We often have schema that build up on each other in chains like this, and sometimes in newer schema we depreciate keys. For small schema like this it may not seem all that useful. But for large schema, it is nice to be able to start from a base and remove and add keys easily.

**Comment by tusharmakkar08** [comment]
Hmm.. I think it would be good to add the inverse functionality of extend, will make the flow smoother. 

`shorten(extend(schema))  == schema`

@alecthomas , What are your views on this?

**Comment by alecthomas** [comment]
I think I'm probably at a -1 on this. Given you can achieve the same result with extend (make the base case, then extend to the two more specific cases), I think it is probably unnecessary.

**Comment by mprager** [comment]
@alecthomas I'm not sure I understand you. How would you extend v0 to v2 in the example above? Given that v0 has a key `c` that is not present in v2.

**Comment by alecthomas** [comment]
You do not do that. You refactor your schemas so that v0 is a superset of everything that requires it:

```
v0 = {
"a": int,
"b": float,
}
```

**Comment by mprager** [comment]
I see what you are saying, but at the time of v0 creation, you will not know what successive versions will look like, as the need for updates would arise over time. If you could identify an ideal subset, this approach would work, but then you likely would not need versioning to begin with. 

If each time a new subset is realized, the solution is to rewrite the base an all extensions up to that point, then I think the solution becomes unmanageable in the long run, as well as being less readable. I won't push the issue any more though, if you don't think it is necessary, the external utility functions work fine for us. Just thought i'd put it out there.
