### ISSUE TITLE
Validation of Strings

### ISSUE THREAD

**Issue by jason-feng** [alecthomas/voluptuous#263]
I am currently attempting to validate this:
`{
    "wordObjects":  [
        {
            "end": 1.3,
            "features": [
                "sos"
            ],
            "start": 1.27,
            "word": "I"},
        {
            "end": 2.2,
            "features": [
                "eos"
            ],
            "start": 1.3,
            "word": "heard"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "a"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "fox"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "walking"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "in"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "the"
        },
        {
            "end": 12.85,
            "features": [
                "sos"
            ],
            "start": 12.79,
            "word": "woods"
        }
    ]
}
`

using the below schema:

`
schema = Schema(
    {
        Required('wordObjects'): [
            {
                'start': float,
                'end': float,
                'word': str,
                'features': [str],
            }
        ]
    }
)
`

However I keep getting an error saying that 
`
{
  "error": "expected str @ data[u'wordObjects'][0][u'features'][0]"
}
`

However clearly it is already a string, I am pretty lost here. Please if you guys could point out what I'm doing wrong, or maybe I found a bug with nested objects

**Comment by alecthomas** [comment]
This works for me on python2:

```python
[aat@cavern:~/Projects/voluptuous]python2
Python 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from voluptuous import *
>>> schema = Schema( { Required('wordObjects'): [ { 'start': float, 'end': float, 'word': str, 'features': [str], } ] } )
>>> schema
<Schema({'wordObjects': [{'start': <type 'float'>, 'end': <type 'float'>, 'features': [<type 'str'>], 'word': <type 'str'>}]}, extra=PREVENT_EXTRA, required=False) object at 0x10f84a050>
>>> data = { "wordObjects": [ { "end": 1.3, "features": [ "sos" ], "start": 1.27, "word": "I"}, { "end": 2.2, "features": [ "eos" ], "start": 1.3, "word": "heard" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "a" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "fox" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "walking" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "in" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "the" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "woods" } ] }
>>> schema(data)
{'wordObjects': [{'start': 1.27, 'end': 1.3, 'features': ['sos'], 'word': 'I'}, {'start': 1.3, 'end': 2.2, 'features': ['eos'], 'word': 'heard'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'a'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'fox'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'walking'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'in'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'the'}, {'start': 12.79, 'end': 12.85, 'features': ['sos'], 'word': 'woods'}]}
>>>
```

And python3:

```python
[aat@cavern:~/Projects/voluptuous]python3
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from voluptuous import *
>>> schema = Schema( { Required('wordObjects'): [ { 'start': float, 'end': float, 'word': str, 'features': [str], } ] } )
>>> data = { "wordObjects": [ { "end": 1.3, "features": [ "sos" ], "start": 1.27, "word": "I"}, { "end": 2.2, "features": [ "eos" ], "start": 1.3, "word": "heard" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "a" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "fox" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "walking" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "in" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "the" }, { "end": 12.85, "features": [ "sos" ], "start": 12.79, "word": "woods" } ] }
>>> schema(data)
{'wordObjects': [{'end': 1.3, 'features': ['sos'], 'start': 1.27, 'word': 'I'}, {'end': 2.2, 'features': ['eos'], 'start': 1.3, 'word': 'heard'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'a'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'fox'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'walking'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'in'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'the'}, {'end': 12.85, 'features': ['sos'], 'start': 12.79, 'word': 'woods'}]}
>>>
```

Are you sure you're on the latest version?

My guess is that there is some kind of unicode mojo going on. Apply this patch to voluptuous and see what it says:

```diff
diff --git a/voluptuous/schema_builder.py b/voluptuous/schema_builder.py
index 042a713..c9165fc 100644
--- a/voluptuous/schema_builder.py
+++ b/voluptuous/schema_builder.py
@@ -634,7 +634,7 @@ def _compile_scalar(schema):
             if isinstance(data, schema):
                 return data
             else:
-                msg = 'expected %s' % schema.__name__
+                msg = 'expected %s but got %s' % (schema.__name__, type(data).__name__)
                 raise er.TypeInvalid(msg, path)

         return validate_instance
```

**Comment by jason-feng** [comment]
Yeah I am on the latest version, yeah it is a unicode issue. What happens is when the JSON gets decoded from the response, it turns it into unicode instead of a str. Thanks for your help!
