### ISSUE TITLE
Should default values fail validation?

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#264]
In using voluptuous, we've come across a few cases where the following code is written:

```python
s = Schema({
    Optional('key', default=None): int,
})
```

This behaves as:

```python
>>> s({})
{'key': None}
>>> s({'key': 3})
{'key': 3}
```

but `s({'key': None})` raises a validation error:

    voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['key']

On one hand, this is true as the schema specifies that the value, if provided, must be of type `int`.

But, on the other hand, the developer may have expected `Optional('key', default=None): int` to behave as `Optional('key', default=None): Any(None, int)` which gives the intended behaviour:

```python
>>> s({})
{'key': None}
>>> s({'key': 3})
{'key': 3}
>>> s({'key': None})
{'key': None}
```

So the question is: if the default value on its own does not validate against the schema of the value, should that raise an error?

I believe this issue is different from https://github.com/alecthomas/voluptuous/issues/233 as that issue is about evaluating nested default values without duplication.

**Comment by tusharmakkar08** [comment]
Hmm.. That's an interesting observation. I believe that since voluptuous is meant to be a validation library it shouldn't distinguish between `s({})` and `s({'key': None})` and hence ideally no error should be thrown. @alecthomas What do you think about this ?

**Comment by alecthomas** [comment]
This is programmer error, obviously, but I think that voluptuous should either catch it at schema construction time or, if not then, definitely at validation time. The latter will probably be easier to implement I suspect.

**Comment by efficiosoft** [comment]
Hi,

I also want to mention another implication of this issue.

    >>> import voluptuous as vol
    >>> schema = vol.Schema({vol.Optional("key", default=0): lambda v: v + 3})
    >>> schema({})
    {'key': 0}
    >>> schema({"key": 10})
    {'key': 13}

I'm using similar constructs to pre-process values after they have been validated, often with something like ``All([int], custom_processor)``. I believe that default values should always go through the validation process, which would also prevent situations like @svisser mentioned from occuring.

Another issue mentioning this problem, although in another context, is https://github.com/alecthomas/voluptuous/issues/233.

I could try to implement this and file a PR, if desired by @alecthomas. Please let me know.

Best regards
Robert

**Comment by efficiosoft** [comment]
Regarding to the PR I offered, I think the changes would need to go into ``def validate_mapping`` in ``schema_builder.py``, but from looking at the code, I don't see a quick and nice way of adding it there, since the validation of keys that are present is completely separated from the filling in of default values, and I don't want to restructure the flow completely without a deep knowledge of voluptuous.

**Comment by svisser** [comment]
As a workaround you could extract the logic into a function and use that both as default and value type (similar to some functions implemented here: https://github.com/alecthomas/voluptuous/blob/master/voluptuous/util.py):

```pycon
>>> import voluptuous as vol
...
... def AdjustByThree(v=0):
...     return v + 3
...
... s = vol.Schema({vol.Optional('key', default=AdjustByThree): AdjustByThree})

>>> s({})
{'key': 3}

>>> s({'key': 10})
{'key': 13}
```

**Comment by efficiosoft** [comment]
Oh, right. I wasn't actually aware that default values can be callables as well... Thanks for this workaround!

**Comment by alecthomas** [comment]
@efficiosoft I think you're right that default values should go through validation. A PR would be welcome, thank you.

**Comment by efficiosoft** [comment]
Ok, PR filed (https://github.com/alecthomas/voluptuous/pull/324).

**Comment by svisser** [comment]
I think this issue is now safe to close?

**Comment by alecthomas** [comment]
Yes, I believe so!
