### ISSUE TITLE
In and Contains are duplicates

### ISSUE THREAD

**Issue by z1IB6p** [alecthomas/voluptuous#268]
The `In` and `Contains` validators are basically exactly the same. `In` came first (present in and before https://github.com/alecthomas/voluptuous/commit/fafc7204d7121645fc0fa18dc9df521431d000be 10 months ago, where as `Contain` was introduced 1 month ago in https://github.com/alecthomas/voluptuous/commit/b23fe91a04131ac9758aade47bd33706177f6477.

I suggest `Contains` is removed - that would break any projects that depend on voluptuous but the upgraded path is very simple so I don't think that's such a big deal.

What do you think?

**Comment by alecthomas** [comment]
Yeah, that is actually really weird. It is a copy paste of code literally 15 lines above it. I can't imagine why I merged it. Anyway, no release has been made with that validator, so removing it will not cause issues. Good call.

**Comment by sfelf** [comment]
Aren't they kind of the opposite of each other? 

```
>>> a = [1, 2, 3]
>>> b = 2
>>> in_validator = In(a)
>>> contains_validator = Contains(b)
>>> in_validator(b)
2
>>> contains_validator(a)
[1, 2, 3]
```

**Comment by alecthomas** [comment]
Hmm, yes, you're right... the descriptions were identical, which was very confusing. I'll revert the revert, and update the description to be more useful.
