### ISSUE TITLE
IsDir, IsFile and PathExists differ between Python 2.7 and Python 3.x

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#270]
In Python 2.7 the following calls:

- ```Schema(IsDir())(3)```
- ```Schema(IsFile())(3)```
- ```Schema(PathExists())(3)```

raise:

    TypeError: coercing to Unicode: need string or buffer, int found

but in Python 3.x they respectively result in:

- voluptuous.error.MultipleInvalid: not a directory
- voluptuous.error.MultipleInvalid: not a file
- voluptuous.error.MultipleInvalid: path does not exist

**Comment by tusharmakkar08** [comment]
Hey @svisser 

Thanks for reporting this inconsistency. I will look into it and get it fixed in next release. 

Thanks.

**Comment by svisser** [comment]
Many thanks for that!
