### ISSUE TITLE
Schema for a list of dict

### ISSUE THREAD

**Issue by derekwallace** [alecthomas/voluptuous#272]
Hi,
I have data that is a list of dict
[{'A' : 'a', 'B': 'b'}, {'A' : 'aa', 'B': 'bb'}]

Is it possible to define a schema to supprt this.
Specifically i want to bound the list length to be between 1 and 5

My first attempt is this. This works and allows unbounded number of the Dict
oSchema = Schema(
   [{'A' : str, 'B'   : str}]
)

is there a way to bound to between 1 and 5?

Thx
derek

**Comment by tusharmakkar08** [comment]
Hey @derekwallace 

I think this is what you require. 

` oSchema = Schema(All([{'A': str, 'B': str}], Length(min=1,max=5)))`

Let me know if this doesn't work according to your requirement. Closing this issue for now.

Thanks

**Comment by derekwallace** [comment]
Yes that works perfectly. Thx.
