### ISSUE TITLE
voluptuous.error.SchemaError: unsupported schema data type 'bytes'

### ISSUE THREAD

**Issue by boramalper** [alecthomas/voluptuous#274]
Hello, I am using the code below to validate but voluptuous raises the exception in the title.

```python

generic_message_schema = {
    voluptuous.Required(b"t"): voluptuous.All(bytes, voluptuous.Length(min=1)),
}
```

Am I doing something wrong or does voluptous not support bytes?

```
$ pip3 show voluptuous
Name: voluptuous
Version: 0.9.3
Summary: # Voluptuous is a Python data validation library
Home-page: https://github.com/alecthomas/voluptuous
Author: Alec Thomas
Author-email: alec@swapoff.org
License: BSD
Location: /home/bora/.pyenv/versions/3.6.0/lib/python3.6/site-packages
Requires: setuptools
```

**Comment by svisser** [comment]
Yeah, the issue seems to be with `voluptuous.Required(b"t")` which raises that error.

https://github.com/alecthomas/voluptuous/blob/master/voluptuous/schema_builder.py#L242-L246

**Comment by alecthomas** [comment]
Seems like a simple fix, PR's welcome, or we'll get to it eventually.

**Comment by boramalper** [comment]
Thanks for the quick solution!
