### ISSUE TITLE
0.10.0 Release 

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#276]
Hey @alecthomas 

As mentioned by @odedfos over [here](https://github.com/alecthomas/voluptuous/issues/259#issuecomment-292137057) , let's release the new major bump version for voluptuous. Any suggestions for the release and release date? 

Thanks.

**Comment by alecthomas** [comment]
@tusharmakkar08 sounds good to me. You have the permissions on PyPi to release, feel free to do it yourself if you like, or I can get to it soon.

**Comment by tusharmakkar08** [comment]
Updated it to 0.10.2 because of some formatting issue.
