### ISSUE TITLE
Remove key if one type, leave it if another?

### ISSUE THREAD

**Issue by lsglick** [alecthomas/voluptuous#282]
Is there a way to remove a key from a dict if it is a specific type, leave it if it is another, and be invalid if it is any other type?

Basically I want:
```
{'my_str': basestring} -> {'my_str': basestring}
{'my_str': None} -> {}
{'my_str': int, list, etc.} -> Invalid
```

I'm trying to use `Requires()` but it doesn't seem to work right.

Things I've tried include:
```
Schema({'my_str': Any(Remove(None), basestring)}) 
Schema({Optional('my_str'): Any(Remove(None), basestring)})
Schema({Remove('my_str'): None, 'my_str': basestring}) 
Schema({'my_str': basestring, Remove('my_str'): None}) 
Schema({'my_str': basestring, Remove(basestring): None})
```

The closest I've gotten is:
```
Schema({v.Remove('my_str'): None}, extra=v.ALLOW_EXTRA)
```
But unfortunately this 1) doesn't provide a way to validate `my_str` is actually a `basestring`, and 2) allows all other extras which I don't want.

Thanks!

**Comment by tusharmakkar08** [comment]
Hey @lsglick 

If I understood your requirements clearly, I guess the following schema would work for your case: 

`Schema(Any({Remove("my_str"): None}, {"my_str": basestring}))`

I will be closing this issue for now. Will reopen if the solution requires additional feature in Voluptuous. 

Thanks.

**Comment by lsglick** [comment]
Thanks for the help @tusharmakkar08!

You're right that your suggested schema would work for my simplified case. But in real usage, that same dict would contain other keys too. So I believe using I'd have to reproduce the dictionary schema twice, one for each possible `my_str` option? And if there were multiple of these "remove if None" keys I wanted, the schema would have to be reproduced exponentially.

e.g.:
```
Schema(Any({'key_1': basestring, ..., 'key_n': basestring, Remove('my_str'): None}, {'key_1': basestring, ..., 'key_n': basestring, 'my_str': basestring}))
```

So a more realistic example for what I want might be:
```
# Doesn't work
Schema({'key1': basestring, RemoveIfNone('my_str'): basestring})
```

With an expected output: 
```
{'key1': 'val1', 'my_str': 'val_str'} -> {'key1': 'val1', 'my_str': 'val_str'}
{'key1': 'val1', 'my_str': None} -> {'key1': 'val1'}
{'key1': 'val1', 'my_str': ['list_val']} -> Invalid
```

It seems discussions in https://github.com/alecthomas/voluptuous/pull/82#issuecomment-51624640 and https://github.com/alecthomas/voluptuous/pull/79#issuecomment-51910712 reference a similar pattern. But its unclear to me if that's supposed to work or if there is another way to get the same functionality.

**Comment by lsglick** [comment]
I did just find one workaround:
```
Schema({'key_1': basestring, Remove(Match('my_str')): None, Match('my_str'): basestring})
```

But that seems like unnecessary overhead, and I can't find why it doesn't work without `Match()`.

**Comment by lsglick** [comment]
Actually I found the change in #86. (Somehow I was looking at an old fork when trying to track this down).

I can't imagine why values would be prioritized over `Requires`? But switching their priorities fixes it locally for me.
