### ISSUE TITLE
Backward incompatibility: error path not available anymore

### ISSUE THREAD

**Issue by brmzkw** [alecthomas/voluptuous#283]
The code below raises a voluptuous error because extra data are forbidden by and empty schema.

```
from voluptuous import Schema

try:
    Schema({})({"extra": "invalid", "extra2": "invalid"})
except Exception as exc:
    print '\n'.join([', '.join(error.path) for error in exc.errors])
```

With voluptuous 0.9.3, the extra keys are displayed ("extra2", "extra").
With voluptuous >=0.10, the error `path` is not longer available and an empty string is displayed.

Is it an expected change, or is it a bug that needs to be fixed?

**Comment by vikbez** [comment]
PR #215 introduced this behaviour: a length check of schema was added [here](https://github.com/alecthomas/voluptuous/pull/215/files#diff-baa3fecf95d431f3822c7bf90a9f99d0R204), so now _compile_dict is never called on an empty dict.

**Comment by alecthomas** [comment]
Agreed, that seems inconsistent.

**Comment by brmzkw** [comment]
Any chance to revert #215 then?

**Comment by kdeldycke** [comment]
Should we close that PR now that #298 has been proposed by @tbillon and merged?
