### ISSUE TITLE
Boolean() validation woes

### ISSUE THREAD

**Issue by untergeek** [alecthomas/voluptuous#286]
```
>>> from voluptuous import *
>>> schema = Schema({ Required('a'): Boolean() })
>>> schema({ 'a': [{'foo':'bar'}]})
{'a': True}
```

Is this expected behavior?  This is the shortened code snippet:
```python
>>> def Boolean(v):
...     if isinstance(v, basestring):
...         v = v.lower()
...         if v in ('1', 'true', 'yes', 'on', 'enable'):
...             return True
...         if v in ('0', 'false', 'no', 'off', 'disable'):
...             return False
...         raise ValueError
...     return bool(v)
```
It seems like it will only return `True` and `False` for the indicated values, and then return `True` for any populated value that is not of type `str` or `unicode`:

Dict:
```
>>> schema({ 'a': {'foo':'bar'}})
{'a': True}
```

Int:
```
>>> schema({ 'a': 99})
{'a': True}
```
Float:
```
>>> schema({ 'a': 123.45})
{'a': True}
```

It doesn't seem like a good idea to validate `Boolean()` if I can pass a list to the schema check and have it accidentally validate as True.

This can be partially solved by using `All(Any(str, unicode), Boolean())`, but this is not what I would _expect_ to need to do with the validator.  The problem I have is that after importing YAML data, `exclude: False` becomes `{'exclude': False}`, rather than `{'exclude': 'False'}`, which leads me to the current ugly, final solution:

```
Any(bool, All(Any(str, unicode), Boolean()))
```

There is nothing in your documentation that informs me of these hoops I have to jump through.  If I didn't read the code, I would have had no idea that it expects a string value.

As far as potential fixes go:
```
>>> def Boolean(v):
...     if isinstance(v, basestring):
...         v = v.lower()
...         if v in ('1', 'true', 'yes', 'on', 'enable'):
...             return True
...         if v in ('0', 'false', 'no', 'off', 'disable'):
...             return False
...         raise ValueError
...     elif isinstance(v, bool):
...         return v
...     else:
...         raise ValueError
...
>>> Boolean(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in Boolean
ValueError
>>> Boolean("1")
True
>>> Boolean("0")
False
>>> Boolean(True)
True
>>> Boolean(False)
False
>>> Boolean({'a':'b'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in Boolean
ValueError
```
It seems pretty straightforward to add the `elif` to test if it's a `bool` before attempting to return `bool(v)`, or more appropriately, `v`, since it's an instance of `bool`.

It could also be modified to work with floats and ints (not just strings of `"1"`, and `"0"`:
```python
def Boolean(v):
    # Make floats into integers
    if isinstance(v, float):
        # Ensure that only 0.0 is 0
        v = 1.0 if v > 0 and v < 1 else v
        v = int(v)
    # Make integers strings for guaranteed comparisons 
    if isinstance(v, int):
        v = str(v)
    if isinstance(v, basestring):
        v = v.lower()
        if v in ('1', 'true', 'yes', 'on', 'enable'):
            return True
        if v in ('0', 'false', 'no', 'off', 'disable'):
            return False
        raise ValueError
    elif isinstance(v, bool):
        return v
    else:
        raise ValueError
```

I'm happy to submit this as a PR if you're satisfied this won't break existing, expected behavior.

**Comment by alecthomas** [comment]
This is expected behaviour and is described in the docstring. If you want an actual bool use `Schema({'a': bool})`.

**Comment by untergeek** [comment]
It's your project, but I don't think it's intuitive, even with the documentation. And the fact that it allows things other than the allowed values seems like bad practice.

**Comment by untergeek** [comment]
Either way, I have a work-around. Thanks for your work on the project.

**Comment by alecthomas** [comment]
I get where you're coming from, but the last line of the docstring is `Non-string values are cast to bool.`. It was intended to be similar to Python's "truthiness", but I think it was poorly named. Ideally it would be named `Truthiness` or something similar. However, it's too late to change the behaviour now, unfortunately.
