### ISSUE TITLE
Build Failing due to coveralls 

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#288]
Hey 

Coveralls stopped supporting Python version < 3.3. Please check the build [here](https://travis-ci.org/alecthomas/voluptuous/jobs/231428779). 

@alecthomas : How should we proceed in this case? 

Thanks.

**Comment by tusharmakkar08** [comment]
Raised [issue](https://github.com/coveralls-clients/coveralls-python/issues/154) in [coveralls](https://github.com/coveralls-clients/coveralls-python) as well.

**Comment by alecthomas** [comment]
We can  probably just remove Python 3.2 from Travis. It was released in 2011, so it's had a good run.
