### ISSUE TITLE
Strange merging two schemas

### ISSUE THREAD

**Issue by v-v-vishnevskiy** [alecthomas/voluptuous#289]
I try to run following code on **0.10.5** version:
```python
from voluptuous import Schema, Required, Optional, Coerce, REMOVE_EXTRA
from datetime import datetime


a = Schema(
    {
        Required('is_active', default=True): Coerce(bool),
        Required('record'): {
            Required('created'): datetime
        }
    },
    extra=REMOVE_EXTRA
)
b = a.extend({
    Optional('images'): list,
    Required('record'): {
        Required('updated'): datetime
    }
})
print(b)
```
Result is:
`<Schema({'is_active': Coerce(bool, msg=None), 'record': {'created': <class 'datetime.datetime'>}, 'images': <class 'list'>, 'record': {'updated': <class 'datetime.datetime'>}}, extra=REMOVE_EXTRA, required=False) object at 0x1128290b8>`

I expected that `created` and `updated` would be in `record` field, but I have two different `record`'s fields.

Also:
```python
print(Required('created') == Required('created'))
```
is `False`

**Comment by svisser** [comment]
I can't seem to reproduce it (Python 3.6.1, voluptuous 0.10.5, Mac OS X). I end up with:

    <Schema({'images': <type 'list'>, 'record': {'updated': <type 'datetime.datetime'>, 'created': <type 'datetime.datetime'>}, 'is_active': Coerce(bool, msg=None)}, extra=REMOVE_EXTRA, required=False) object at 0x10c24d790>

```python
>>> pprint.pprint(b.schema)
{'images': <type 'list'>,
 'is_active': Coerce(bool, msg=None),
 'record': {'created': <type 'datetime.datetime'>,
            'updated': <type 'datetime.datetime'>}}
```

What version of Python are you running?

**Comment by v-v-vishnevskiy** [comment]
I use python 3.6.1, voluptuous 0.10.5 and macOS Sierra 10.12.4
Python was installed through `pyenv`.

**Comment by svisser** [comment]
I can reproduce it in voluptuous 0.9.3:

```
>>> print(b)
<Schema({'record': {'created': <class 'datetime.datetime'>}, 'record': {'updated': <class 'datetime.datetime'>}}, extra=PREVENT_EXTRA, required=False) object at 0x101c59e48>
>>> print(voluptuous.__version__)
0.9.3
```

but not in 0.10.2 onwards:

```
>>> print(b)
{'record': {'created': <class 'datetime.datetime'>, 'updated': <class 'datetime.datetime'>}}
>>> print(voluptuous.__version__)
0.10.2
```

Is it possible that your installed version of voluptuous is 0.9.3?

**Comment by v-v-vishnevskiy** [comment]
Oh, I just install **voluptuous 0.10.5** on my home laptop and have no this issue!
Ok, I will clarify in Monday of what version installed in my work computer, but I saw from `pip list` output that I have  **voluptuous 0.10.5**...
On Monday I will answer.
Thank you!

**Comment by alecthomas** [comment]
Feel free to reopen if you find a bug.
