### ISSUE TITLE
Support for sets

### ISSUE THREAD

**Issue by nowox** [alecthomas/voluptuous#292]
The following gives me an error: 

```
>>> Schema({int})(set([42]))
SchemaError: unsupported schema data type 'set'
```

The workaround I found is: 

```
>>> Schema(All(lambda x: {k: None for k in x}, {int: None}, lambda x: set(x.keys())))(set([42]))
{42}
```

**Comment by nowox** [comment]
I wasn't aware of `Set` mentioned in the documentation

**Comment by alecthomas** [comment]
Ideally your initial approach should work, so I'll keep this open until I can implement it.

**Comment by tusharmakkar08** [comment]
Closing this issue since PR has been merged.
