### ISSUE TITLE
Partial validation with @validate?

### ISSUE THREAD

**Issue by AndreaCrotti** [alecthomas/voluptuous#296]
I was a bit surprised that the following snippet doesn't work
```
import voluptuous as V

API_SCHEMA = V.Schema({
    V.Required('uri'): str,
}, extra=V.ALLOW_EXTRA)

print(API_SCHEMA({'uri': 'hello', 'other': 'hello'}))


@V.validate(data=API_SCHEMA)
def func(a, data):
    print(data)


func(10, {'uri': 'hello', 'other': 'hello'})
```

And it gives this error:

```
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['a']
```

I can't find any flag (or tests supporting the idea that there is a way) to do this kind of partial validation of argument types.
Is it not possible on purpose for some reason?
Thanks!

**Comment by tusharmakkar08** [comment]
Hey @AndreaCrotti 

This looks like a bug. Thanks for reporting it out. 
Will work on it soon. Meanwhile, if you are interested you can open a PR for the same.

Regards,
TM

**Comment by tusharmakkar08** [comment]
Closed via https://github.com/alecthomas/voluptuous/pull/303
