### ISSUE TITLE
RFC: Add description attribute to Required/Optional

### ISSUE THREAD

**Issue by balloob** [alecthomas/voluptuous#305]
So I'm not sure if this should be even a thing in voluptuous, but since more users of this lib might be interested I thought I'll bring it up.

We use voluptuous in [Home Assistant](https://github.com/home-assistant/home-assistant) and it's awesome. For some of the things that we have voluptuous validate, we would like to generate a schema of what is allowed.

To this end I started an experiment a while ago called [voluptuous form](https://github.com/balloob/voluptuous_form). I'm looking into reviving this effort but there is one missing piece of the puzzle: description of the fields.

Would description be something that would make sense to add to Voluptuous?

Potential syntax:

```python
import voluptuous as vol

SCHEMA = vol.Schema({
  vol.Required('name', description='The name of the user.'): str,
  vol.Required('age', description='The age of the user.'): int,
})
```

**Comment by tusharmakkar08** [comment]
Hey @balloob 

I think an optional `description` field will make Voluptuous objects more readable. I look Voluptuous Form as `pretty print` for voluptuous Schemas. @alecthomas, What's your viewpoint on this? 

Also, if we have to go by adding the field, We can make it more generic and extend it to `Marker` class. 

Thanks

**Comment by alecthomas** [comment]
Several other people have professed interest in being able to introspect Voluptuous schemas, and I think it is a good idea, but the approach of using lambda's or functions for validation doesn't lend itself cleanly to this, I think.

For example, given this schema:

```python
s = Schema(lambda v: v > 10)
```

There's no good way to introspect that into something useful.

That said, I don't think it's a bad idea to add descriptions where possible.

**Comment by balloob** [comment]
Thanks for the feedback. I like @tusharmakkar08 idea to add it to `Marker`, would you be okay with that @alecthomas ?

**Comment by tusharmakkar08** [comment]
Yes, You can proceed.
