### ISSUE TITLE
Support for Python 3.4+ enums

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#309]
This is a ticket to explore the possibility of adding support for Python 3.4+ enums to voluptuous.

So far it's possible to write:

```python
import enum

from voluptuous import In, Schema

class MyEnum(enum.Enum):
    A = 'a'
    B = 'b'

s = Schema(In(item.value for item in MyEnum))
s('a')
```

but perhaps it would be nice if it could be written as the following?

```python
s = Schema(In(MyEnum))
```

or:

```python
s = Schema(MyEnum)
```

**Comment by svisser** [comment]
It appears it's already possible to write:

```
t = Schema(Coerce(MyEnum))
```

**Comment by alecthomas** [comment]
That is working as intended.

The following is consistent with the general approach of Voluptuous, as is your use of `Coerce(MyEnum)`.

```python
import enum

from voluptuous import In, Schema


class MyEnum(enum.Enum):
    A = 'a'
    B = 'b'


s = Schema(MyEnum)
s(MyEnum.A)
```
