### ISSUE TITLE
 About multiple same key，In dict

### ISSUE THREAD

**Issue by flybaozi** [alecthomas/voluptuous#312]
There are multiple identical keys in a dict, which is correct if you only need to match the value of one key. How can it be a better operation?
```
{
	"code": 0,
	"data": {
		"com": [
			{
				"name": "pear",
				"status": "open",
				"tags": "one"
			},
			{
				"name": "apple",
				"status": "open",
				"tags": "one"
			},
		]
	},
	"msg": "thks！"
}
```

I just need to verify that the name is equal to pear

thks~

**Comment by alecthomas** [comment]
Are you looking for `{"name": Any("pear", "apple"), ...}`?

**Comment by tusharmakkar08** [comment]
Closing issue because of no response from author.
