### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fabaff** [alecthomas/voluptuous#313]
Is there a new release planned in the near future? I'm especially interested in #307. Thanks.

**Comment by dtao** [comment]
I am also curious if a new release will be coming any time soon.

Not trying to be pushy. Just curious!

**Comment by svisser** [comment]
There is a new release now :)

**Comment by alecthomas** [comment]
[0.11.1](https://pypi.org/project/voluptuous/0.11.1/)

**Comment by fabaff** [comment]
@alecthomas, thanks a lot.
