### ISSUE TITLE
Link to pytest-voluptuous plugin in README

### ISSUE THREAD

**Issue by tuukkamustonen** [alecthomas/voluptuous#320]
Hi, I released a pytest plugin that integrates with voluptuous. It's called, surprise suprise, [pytest-voluptuous](https://github.com/F-Secure/pytest-voluptuous)! Find it at [PyPI](https://pypi.python.org/pypi/pytest-voluptuous).

Would you mind if we linked to it in the README? Maybe even right away in the first section (before `Contact`). On the same go, you could go over the [README](https://github.com/F-Secure/pytest-voluptuous/blob/master/README.rst) and verify that it makes sense in the first place :)

I published it in a [Reddit post](https://www.reddit.com/r/Python/comments/7pmijj/released_pytestvoluptuous_a_nifty_little_pytest/) and while it unfortunately didn't get much attention, there's also a line or two about the background of the library.

**Comment by alecthomas** [comment]
Looks useful!

Sure, feel free to add it to the README. There is a section at the bottom about related libraries, I think there is fine.
