### ISSUE TITLE
Suggestion/discussion - schema part or combining schemas

### ISSUE THREAD

**Issue by guyarad** [alecthomas/voluptuous#327]
Didn't see that anything like is supported.
The use-case is wanted to compose a new schema from 2 (or possibly more) other schemas. 
```python
SCHEMA1 = Schema(...)
SCHEMA2 = Schema(...)
COMBINED_SCHEMA = Schema(parts=[
    SCHEMA1,
    SCHEMA2])
```

Of course we can do something like: `COMBINED_SCHEMA = All(SCHEMA1, SCHEMA2)`
But that's tricky because what if I have `extra=REMOVE_EXTRA` in either of the schema parts? 
This could happen if in some cases I want to use these schemas in other context that aren't combined, in which I want to PREVENT_EXTRA, for instance. 

So when used with imagined `parts` attribute it should temporarily ignore `extra` configuration and apply later on, somehow indicating which fields were extraneous.
Maybe implement further logic such as:
- if both schemas were configured as PREVENT_EXTRA, remove the extraneous fields
- if one of them was ALLOW_EXTRA all fields are allowed. 
- if both were marked REMOVE_EXTRA, remove them

What do you think?

**Comment by guyarad** [comment]
One way to achieve this goal is support initialization of a Schema from a Schema instance, modifying the extra so we'll have something like:
```python
SCHEMA1 = Schema(..., extra=PREVENT_EXTRA)
SCHEMA1_ALLOW_EXTRA = Schema(init_schema=SCHEMA1, extra=ALLOW_EXTRA)
SCHEMA2 = Schema(..., extra=PREVENT_EXTRA)
SCHEMA2_ALLOW_EXTRA = Schema(init_schema=SCHEMA2, extra=ALLOW_EXTRA)

COMBINED_SCHEMA = All(SCHEMA1, SCHEMA2)
```

This implementation, however, will not support removing any extra field...

**Comment by alecthomas** [comment]
I feel like `Schema.extend()` could be made to work for this situation?

**Comment by guyarad** [comment]
Wasn't aware of this own - I suppose it can. Could work pretty well actually - thanks!
