### ISSUE TITLE
Permission issues in PyPI source tarballs

### ISSUE THREAD

**Issue by felixonmars** [alecthomas/voluptuous#333]
The files inside the PyPI source tarballs are 0640, including those under `voluptuous.egg-info/`. This causes setuptools to install these metadata with 640 permission (not world readable). It would be okay to either exclude egg-info from the source tarball or make them world-readable (644).

**Comment by tusharmakkar08** [comment]
Thanks for the suggestion. Would take this into consideration from the next release.

**Comment by AWhetter** [comment]
Was this taken into consideration in subsequent releases? I'm seeing this in the latest version (0.11.7) and the previous versions that I've checked.
