### ISSUE TITLE
Validation behaviour changed.

### ISSUE THREAD

**Issue by amateja** [alecthomas/voluptuous#334]
Hi.

Schema validation in version 0.11.1 validates also default values of optional parameters. Is that change intentional?

```python
from voluptuous import Coerce, Optional, Schema

foo = Schema(
    {
        Optional('bar', default=None): Coerce(int)
    }
)
foo({})
```

**Comment by alecthomas** [comment]
Yes, that is correct. It's mentioned in the [CHANGELOG](https://github.com/alecthomas/voluptuous/blob/master/CHANGELOG.md). If you want to allow `None` as a value you'll need to add it to your validation (eg. `Any(None, Coerce(Int))`).

**Comment by amateja** [comment]
Indeed. Thank you.
