### ISSUE TITLE
Change reference in the title of this repo to new pypi.org

### ISSUE THREAD

**Issue by elipavlov** [alecthomas/voluptuous#338]
Currently in the title of this repo we see http://pypi.python.org/pypi/voluptuous, and this link redirect customers to new page https://pypi.org/project/voluptuous/.

In the future pypi maintainers going to remove redirect and link will be unavailable.
https://packaging.python.org/guides/migrating-to-pypi-org/#browsing-packages

**Comment by alecthomas** [comment]
Done!
