### ISSUE TITLE
SchemaError: unsupported schema data type 'set' ?

### ISSUE THREAD

**Issue by lotusirous** [alecthomas/voluptuous#346]
I run the example code in section [Sets and frozensets](https://github.com/alecthomas/voluptuous#sets-and-frozensets)

> Sets and frozensets are treated as a set of valid values. Each element in the schema set is compared to each value in the input data

I used python 3.6.5.
```
$ python --version
Python 3.6.5
```

```py
import voluptuous
print(voluptuous.__version__) # '0.11.1'

from voluptuous import Schema
schema = Schema({42})
```

Why does it raise voluptuous.error.SchemaError: unsupported schema data type 'set' ?

```py

Traceback (most recent call last):
  File "t.py", line 2, in <module>
    schema = Schema({42})
  File "/home/trongkha/.local/py3/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 202, in __init__
    self._compiled = self._compile(schema)
  File "/home/trongkha/.local/py3/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 296, in _compile
    type(schema).__name__)
voluptuous.error.SchemaError: unsupported schema data type 'set'
```

**Comment by tusharmakkar08** [comment]
Hey @lotusirous 

This has been added in master but hasn't been released yet. For more discussion on this please refer: https://github.com/alecthomas/voluptuous/issues/292 

Closing this issue for now.

Thanks.
