### ISSUE TITLE
one test fails with voluptuous > 0.11

### ISSUE THREAD

**Issue by buzzdeee** [alecthomas/voluptuous#362]
I was looking into updating the voluptuous package on OpenBSD. The current version there is 0.10.5, which, when run regress tests, all 165 tests pass.

now updating, the one test fails:

```
======================================================================
FAIL: Doctest: voluptuous.util.SetTo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for voluptuous.util.SetTo
  File "/home/ports/pobj/amd64/py-voluptuous-0.11.1/voluptuous-0.11.1/voluptuous/util.py", line 84, in SetTo

----------------------------------------------------------------------
File "/home/ports/pobj/amd64/py-voluptuous-0.11.1/voluptuous-0.11.1/voluptuous/util.py", line 90, in voluptuous.util.SetTo
Failed example:
    s("foo")
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest voluptuous.util.SetTo[2]>", line 1, in <module>
        s("foo")
      File "/home/ports/pobj/amd64/py-voluptuous-0.11.1/voluptuous-0.11.1/voluptuous/schema_builder.py", line 271, in __call__
        raise er.MultipleInvalid([e])
    MultipleInvalid: expected int
----------------------------------------------------------------------
Ran 189 tests in 2.677s

FAILED (failures=1)
*** Error 1 in . (Makefile:27 'do-test')
*** Error 1 in . (/home/ports/infrastructure/mk/bsd.port.mk:2762 '/home/ports/pobj/amd64/py-voluptuous-0.11.1/.test_done')
*** Error 1 in /home/ports/devel/py-voluptuous (/home/ports/infrastructure/mk/bsd.port.mk:2412 'test')

```

tested on OpenBSD 6.4 amd64 with python-2.7.15 and 3.6.6, and tested py-voluptuous up to 0.11.5, and always this single test fails.
Since there are more tests now, don't know if this is a new test failing, or an old test that was working previously.

**Comment by alecthomas** [comment]
Have you tried master?

**Comment by buzzdeee** [comment]
Hi,

not sure if I do something wrong. for the released versions, I use the ports infrastructure.
There, when I run nosetests, I see it's running, for example the: 0.11.5:
Ran 199 tests in 1.524s
with the one error.

when I download the 0.11.5 tarball from GitHub, and from pypi, or take git clone of master, and run nosetests, I only see:
Ran 150 tests in 1.012s

I seem to be unable to find out where the other more tests come from. The ports infrastructure tarball is fetching the same from pypi, I checked md5 sum, both the same.

So, when I run the nosetest -v in the ports build environment I get:
```

Doctest: voluptuous.util.Capitalize ... ok
Doctest: voluptuous.util.DefaultTo ... ok
Doctest: voluptuous.util.Lower ... ok
Doctest: voluptuous.util.Set ... ok
Doctest: voluptuous.util.SetTo ... ok
Doctest: voluptuous.util.Strip ... ok
Doctest: voluptuous.util.Title ... ok
...
and some time later:
Doctest: voluptuous.schema_builder.validate ... ok
Doctest: voluptuous.util.Capitalize ... ok
Doctest: voluptuous.util.DefaultTo ... ok
Doctest: voluptuous.util.Lower ... ok
Doctest: voluptuous.util.Set ... ok
Doctest: voluptuous.util.SetTo ... FAIL
Doctest: voluptuous.util.Strip ... ok
Doctest: voluptuous.util.Title ... ok
Doctest: voluptuous.util.Upper ... ok
```

so it runs some of the tests twice, and on the second run the mentioned test fails.

When I run:
nosetests --with-doctest -v
in the extracted directory, then it doesn't run these tests twice, and it just passes all.

Maybe there is something odd in the setup of how nose is running from the ports tree,
I need to see. At least it runs the doctests automatically, so there might be something more.

**Comment by alecthomas** [comment]
0.11.5 is the latest release and all the tests run fine for me 🤷‍♂️
