### ISSUE TITLE
Exclusive and Inclusive are missing in Readme

### ISSUE THREAD

**Issue by m-aciek** [alecthomas/voluptuous#363]
Documentation is missing descriptions of Exclusive and Inclusive objects.

**Comment by svisser** [comment]
I'm not sure everything fits in the readme; there is documentation here though:

- http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#voluptuous.schema_builder.Exclusive
- http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#voluptuous.schema_builder.Inclusive

**Comment by spacegaier** [comment]
I agree, ReadMe is not intended to be a compete documentation (one could argue the current ReadMe is way too long and somewhat mimics a documentation light).
