### ISSUE TITLE
Coerce(float)

### ISSUE THREAD

**Issue by HavardLine** [alecthomas/voluptuous#365]
Hi There!

 We validate XML input and voluptuous seems to be great for this.

The code bellow worked fine for validating and converting integer strings. I guess it will also work fine for strings like "1.5". In Norway we use comma as decimal separator. Strings like "1,5" is not accepted.

Do you have any tips for how to convert and accept the comma decimal separator?

`schema = Schema({'LENGTH': Coerce(float)})`

I do not have much experience using voluptuous. Sorry in advance if the issue is already addressed.

**Comment by svisser** [comment]
You could do:

```python
schema = Schema({'LENGTH': Any(Coerce(float), All(Replace(',', '.'), Coerce(float)))})
```

which accepts things that can be converted to float or strings that can be converted to float after replacing the `,` by `.`:

```pycon
>>> schema({'LENGTH': '3'})
{'LENGTH': 3.0}
>>> schema({'LENGTH': '3.0'})
{'LENGTH': 3.0}
>>> schema({'LENGTH': '3,0'})
{'LENGTH': 3.0}
```

**Comment by HavardLine** [comment]
Yes this works! I was still confused until reading doc for the All class.
> The output of each validator is passed as input to the next.

Thanks for a fast and accurate reply @svisser
