### ISSUE TITLE
DeprecationWarning in python 3.7 with pytest

### ISSUE THREAD

**Issue by voidpp** [alecthomas/voluptuous#367]
pytest shows this warning message after I run a test which is contains a voluptuous.Schema instance

voluptuous version: 0.11.5

```
/Users/voidpp/.virtualenvs/configpp-371/lib/python3.7/site-packages/voluptuous/schema_builder.py:283
  /Users/voidpp/.virtualenvs/configpp-371/lib/python3.7/site-packages/voluptuous/schema_builder.py:283: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if isinstance(schema, collections.Mapping):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by svisser** [comment]
@voidpp thanks for reporting this DeprecationWarning!

There's now a fix for this on the master branch so I'm closing this issue: https://github.com/alecthomas/voluptuous/commit/e6ef8afbbca2f3e777df4ef5eef528709ab697ed.

**Comment by SethMMorton** [comment]
Is there any timeline on getting a new voluptuous release to PyPI that includes this patch?

**Comment by spacemanspiff2007** [comment]
Yea - that would be really nice!

**Comment by svisser** [comment]
I personally can't create a new release but I have created a pull request with the latest changes (https://github.com/alecthomas/voluptuous/pull/398) to get us closer to a new release.

**Comment by spacemanspiff2007** [comment]
Thank you very much @svisser !

**Comment by alecthomas** [comment]
0.11.7 released.
