### ISSUE TITLE
Schema.extend is not compatible with Schema subclasses (affects pytest-voluptuous)

### ISSUE THREAD

**Issue by himikof** [alecthomas/voluptuous#370]
The [pytest-voluptuous](https://github.com/f-secure/pytest-voluptuous) integration package makes use of a `Schema` subclass (`S`) to implement concise pytest assertion syntax.
It looks like this:
```python
   assert S({
      'info': Partial({
          'package_url': 'https://pypi.org/project/pytest/',
          'platform': 'INVALID VALUE',
          'description': Length(max=10),
          'downloads': list,
          'classifiers': dict,
      }),
      'releases': dict,
      'urls': int
   }) == resp.json()
```

But the problem is that the `S(...).extend` returns `Schema`, not `S`, which breaks pytest integration after using `extend`.
If `Schema.extend` behaved more like a `@classmethod` and returned an instance of `type(self)`, this use case would just work.

**Comment by alecthomas** [comment]
Seems reasonable. PRs welcome.

**Comment by svisser** [comment]
@himikof thanks for reporting this issue!

There is now a fix for this on the master branch so I'm closing this issue: https://github.com/alecthomas/voluptuous/commit/e11b20ac3973523773381b7292746719c7cbd10b.
