### ISSUE TITLE
Lower() and similar functions convert unicode to str

### ISSUE THREAD

**Issue by lcosmin** [alecthomas/voluptuous#374]
Is it the expected behavior for `Lower()` to convert an unicode string to a plain string (Python 2) ? 

Example:

```
>>> from voluptuous import Schema, Lower
>>> s = Schema(Lower)
>>> s('asd')
'asd'
>>> s(u'asd')
'asd'
>>> type(s(u'asd'))
<type 'str'>
```

**Comment by svisser** [comment]
I think you're right; in Python 2 those functions should return a unicode string when a unicode string is passed in.

**Comment by svisser** [comment]
@lcosmin thanks for reporting this issue!

There is now a fix for this on the master branch so I'm closing this issue: https://github.com/alecthomas/voluptuous/commit/2f8412a3d8cfd9ce8df5d46066415d8de2388949.
