### ISSUE TITLE
Schema extends a list of dict objects

### ISSUE THREAD

**Issue by 3dw1np** [alecthomas/voluptuous#376]
I am trying to extend a nested schema definition inside a list:

`
>>> t = Schema({
...     'delivery_addresses': All([{
...             Required('name'): unicode
...     }])
... })

>>> t = t.extend({
...     Required('delivery_addresses'): [{
...             Required('geohash'): unicode
...     }]
... })

>>> print(t)
{u'delivery_addresses': [{u'geohash': <type 'unicode'>}]}
`

But as you can see, it's not merging the dict definition, it's replacing.

**Comment by alecthomas** [comment]
You can only replace or add keys.
