### ISSUE TITLE
pypi description not rendering properly since move to MD

### ISSUE THREAD

**Issue by cjw296** [alecthomas/voluptuous#389]
Just noticed https://pypi.org/project/voluptuous/.

Looks like the markdown isn't being rendered. There's something that can be done to make this work now, but I can't remember what it was...

**Comment by svisser** [comment]
I think there is a check command according to the README here: https://github.com/pypa/readme_renderer

**Comment by spacegaier** [comment]
I cannot see any rendering issues. Since the original post does not contain a screenshot or explanation what exactly is wrong, I assume this is already fixed?

**Comment by cjw296** [comment]
Yep, looks fixed.
