### ISSUE TITLE
Esphome fails "TypeError: __init__() got an unexpected keyword argument 'required'"

### ISSUE THREAD

**Issue by greypanda** [alecthomas/voluptuous#405]
I am having a problem after the last update to esphome. It's getting the following error:

/local/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'

That line reads: return result_cls(result, required=result_required, extra=result_extra).
I "fixed" it by removing the "required=result_required" parameter, but that is just a band-aide.

It also fails with Python 3.6.8.

**Comment by alecthomas** [comment]
What is esphome? Why are you telling me? Report it to them.
