### ISSUE TITLE
Default to other key in dict

### ISSUE THREAD

**Issue by roflcoopter** [alecthomas/voluptuous#406]
I have a dict in this format:
```{'cameras': [{'name': 'Cam1', 'mqtt_name': 'cam_one'}, {'name': 'Cam2'}]}```

I would like my schema to default ```mqtt_name``` to ```name```.
So given the input above, i would like this to be the result:
```{'cameras': [{'name': 'Cam1', 'mqtt_name': 'cam_one'}, {'name': 'Cam2', 'mqtt_name': 'Cam2'}]}```

Is this possible in any way?

**Comment by svisser** [comment]
It can be done using the approach in this section: https://github.com/alecthomas/voluptuous#multi-field-validation:

```python
from voluptuous import All, Optional, Required, Schema

def ensure_mqtt_name(camera_data):
    for camera in camera_data['cameras']:
        if 'mqtt_name' not in camera:
            camera['mqtt_name'] = camera['name']
    return camera_data

s = Schema(
    All({
        Required('cameras'): [{
            Required('name'): str,
            Optional('mqtt_name'): str
        }]
    },
    ensure_mqtt_name
    ),
)

# s({'cameras': [{'name': 'Cam1', 'mqtt_name': 'cam_one'}, {'name': 'Cam2'}]})
# gives:
# {'cameras': [{'name': 'Cam1', 'mqtt_name': 'cam_one'}, {'name': 'Cam2', 'mqtt_name': 'Cam2'}]}
```

**Comment by roflcoopter** [comment]
Brilliant! Didn't think of it this way, works perfectly.
