### ISSUE TITLE
./voluptuous/schema_builder.py", line 237

### ISSUE THREAD

**Issue by kentatoi** [alecthomas/voluptuous#407]
Hi, 

I have an issue when I am trying to install. 

> Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    version = __import__('voluptuous').__version__
  File "./voluptuous/__init__.py", line 3, in <module>
    from voluptuous.schema_builder import *
  File "./voluptuous/schema_builder.py", line 237
    for k, v in iteritems(value)}
      ^

Is it just me ? I am running the setup install on RedHat 6.10 (Santiago),
Python 2.6

Thanks for your help

**Comment by alecthomas** [comment]
Python 2.6 is not supported.

**Comment by alecthomas** [comment]
Sorry, that was a bit curt, but only 2.7+ is supported, so please upgrade your Python version.
