### ISSUE TITLE
'Extra key not allowed' - key is in schema

### ISSUE THREAD

**Issue by FabioRosado** [alecthomas/voluptuous#410]
Hello,

I'm trying to use voluptuous with opsdroid to validate our yaml files. Our parsers is a list containing dictionaries, which looks like this:

```python
parsers: [{'name': 'watson', 'gateway': 'gateway', 'assistant-id': 'long-id', 'access-token': 'token'}, {'name': 'regex', 'enabled': True}]
```

My schema looks like this (it's probably wrong since I been doing guesswork and playing around. I wanted to check if any of these dicts are present in the parsers and if it is, check the required fields of them.

```python
Optional('parsers', default=list): voluptuous.All([
        Optional({
            Required('name', default="watson"): str,
            Required('gateway', msg="Watson Parser required param not provided"): str,
            Required('assistant-id', msg="Watson Parser required param not provided"): str,
            Required('access-token', msg="Watson Parser required param not provided"): str,
        }),
        Optional({
            Required('name', default='regex'): str,
            Required('enabled', msg="Regex Parser required param not provided"): bool,
        })])
```

This is the error I'm getting:

```
Configuration contains an error - extra keys not allowed @ data['parsers'][1]['enabled']
```

So the parser regex does have enabled and is marked as required on the schema, not sure why I'm getting an extra key error.

Any idea why this is happening or if I should be doing things differently?

Thank you for the help 👍

**Comment by svisser** [comment]
I think it's because the library is getting confused as `'name'` is used in both parser objects so it's trying to validate `data['parsers'][1]` against the first validator in the list.

The following schema seems to better express what you want:

```python
from voluptuous import *

s = Schema({
    Optional('parsers', default=list): [
        Any(
            {
                Required('name', default="watson"): str,
                Required('gateway', msg="Watson Parser required param not provided"): str,
                Required('assistant-id', msg="Watson Parser required param not provided"): str,
                Required('access-token', msg="Watson Parser required param not provided"): str,
            },
            {
                Required('name', default='regex'): str,
                Required('enabled', msg="Regex Parser required param not provided"): bool,
            }
        )
    ]
})
```

**Comment by FabioRosado** [comment]
Thank you for the reply. Using the `Any` method didn't help because all the required fields would be just skipped if one exists in the config.

This problem made us discuss our configuration layout and made us decide to change the layout to divide the modules by name - so the watson parser would be set like such `parsers: { watson: {'gateway': xyz, ...}}` this made it possible to check if each individual module has the expected params.

I am closing the issue now thank you once more 😄
