### ISSUE TITLE
`Required` flag not set properly after #379 fix

### ISSUE THREAD

**Issue by EarQuack** [alecthomas/voluptuous#419]
Following test (this will be a new test, if accepted) fails:

```python
def test_new_required_test():
    schema = Schema({
        'mykey': All(int, Range(1, 20)),
    }, required=True)
    assert_true(schema.required)
```

Suspect problem was introduced in #379 

Will propose a solution and issue pull request to fix

**Comment by EarQuack** [comment]
@alecthomas Please assign me #419 and I will propose solution and passing test.  Best regards!

**Comment by tusharmakkar08** [comment]
Assigned @EarQuack
