### ISSUE TITLE
Discrepancy between tags/Github releases and PyPi

### ISSUE THREAD

**Issue by Toshakins** [alecthomas/voluptuous#421]
Hello, firstly, I would like to thank you for the library, I think it's quite nice piece of software! 🥇 

Have a question, I noticed that PyPi shows two releases that aren't present in Github release tab. Also, there are no reference tags. Is it because release process changed somehow? Is it done on purpose? If not, do you need any help with the fix?

Thanks in advance and sorry for bothering.

**Comment by spacegaier** [comment]
@alecthomas Bump. Would indeed be quite interesting to know, how this is going to be handled, especially now that the project is in this "Contribution only" mode.

**Comment by alecthomas** [comment]
PyPi is the canonical source.
