### ISSUE TITLE
Differentiate int and bool

### ISSUE THREAD

**Issue by gokulnathck** [alecthomas/voluptuous#443]
In python, bool is a subclass of int.
So if you try to check a boolean value is integer datatype, it's always True.
So to overcome this, do this check.
![Screenshot from 2021-01-28 06-44-47](https://user-images.githubusercontent.com/68318175/106075795-59570180-6134-11eb-8859-db5d0064d239.png)

**Comment by alecthomas** [comment]
What does this have to do with voluptuous? It does the correct thing for bools:

```pycon
>>> s = Schema({"hello": bool})
>>> s({"hello": 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected bool for dictionary value @ data['hello']
>>> s({"hello": True})
{'hello': True}
```

**Comment by gokulnathck** [comment]
> What does this have to do with voluptuous? It does the correct thing for bools:
> 
> ```
> >>> s = Schema({"hello": bool})
> >>> s({"hello": 1})
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 594, in validate_dict
>     return base_validate(path, iteritems(data), out)
>   File "/Users/aat/Projects/voluptuous/voluptuous/schema_builder.py", line 432, in validate_mapping
>     raise er.MultipleInvalid(errors)
> voluptuous.error.MultipleInvalid: expected bool for dictionary value @ data['hello']
> >>> s({"hello": True})
> {'hello': True}
> ```

Give boolean value for integer datatype, not a string datatype.

**Comment by alecthomas** [comment]
As this is consistent with Python, it's debatable whether it's a bug.

**Comment by gokulnathck** [comment]
While checking for an integer datatype, if a boolean value is given.
We can eliminate it by using the following condition, such as:
if (value == 1 or value == 0) and isinstance(value, bool):
       raise Invalid('Invalid input for type integer')

**Comment by alecthomas** [comment]
After thinking about this more, I don't think this should be part of the library. The current behaviour is consistent with Python's type system. If you do need this behaviour though, It's straightforward to write a custom validator.
