### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by dickkniep** [alecthomas/voluptuous#444]
In 0.12.1 in schema_builder.py it is using a deprecated method to import collections. 
`    def _compile(self, schema):
        if schema is Extra:
            return lambda _, v: v
        if schema is Self:
            return lambda p, v: self._compiled(p, v)
        elif hasattr(schema, "__voluptuous_compile__"):
            return schema.__voluptuous_compile__(self)
        if isinstance(schema, Object):
            return self._compile_object(schema)
        if isinstance(schema, collections.Mapping):
            return self._compile_dict(schema)
        elif isinstance(schema, list):
            return self._compile_list(schema)
        elif isinstance(schema, tuple):
            return self._compile_tuple(schema)
        type_ = type(schema)
`

**Comment by alecthomas** [comment]
PRs welcome.

**Comment by spacegaier** [comment]
@dickkniep Are you sure that you are using 0.12.1? I am asking because the warning you reported should have been fixed already by this PR from 0.11.7: https://github.com/alecthomas/voluptuous/pull/371

Did you do anything special to get this warning?
