### ISSUE TITLE
Version 0.13.0 starts using enum which breaks Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [alecthomas/voluptuous#468]
Version 0.13.0 releaed recently and starts using the Python "enum" module. That module was introduced in Python 3.4, and there is a backport package available that supports Python 2.7.

The issue is that use if "enum" was introduced unconditionally, and without taking care of Python 2.7.

Option to fix:
* Since a backport package for enum is available (enum34), that could be used. However, voluptous does not seem to have any provisions currently to specify dependent packages, so that would need to be added as well.
* Remove support for Python 2.7 in a version 0.13.1 and drop version 0.13.0 from pypi. The latter is required to avoid that Python 2.7 users install it.

Circumvention for Python 2.7 users: pin voluptous to <0.13.0

**Comment by spacegaier** [comment]
We have already added a fix in the master branch here that skips the not working coding if `Enum` is not available at runtime. We need to release a new minor version with that fix: https://github.com/alecthomas/voluptuous/pull/454

**Comment by andy-maier** [comment]
Sorry for the delay in responding.

I used 0.13.1 in our https://github.com/zhmcclient/zhmc-ansible-modules project where the issue originally surfaced, and it works fine on Python 2.7: https://github.com/zhmcclient/zhmc-ansible-modules/actions/runs/3764908145/jobs/6399835578

Thanks much for fixing it!
