### ISSUE TITLE
Description argument not documented

### ISSUE THREAD

**Issue by steverep** [alecthomas/voluptuous#471]
The `description` argument for the `Marker` class (or any subclass) is not documented anywhere, so it's unclear what's allowed and how it affects the schema.

**Comment by spacegaier** [comment]
You can see in the PR that added that option (https://github.com/alecthomas/voluptuous/pull/307) it is not really used inside the library itself, but allows having a description that can then be used by the schema creator if required, e.g. for some introspection, see this issue with the reasoning behind that feature: https://github.com/alecthomas/voluptuous/issues/305

There is nothing specifically allowed for `description`. You can pass anything in.

**Comment by steverep** [comment]
Thanks for the explanation.  Pasting something similar into the doc string would have saved me some confusion.
