### ISSUE TITLE
No way to install voluptuous??

### ISSUE THREAD

**Issue by Aryavui** [alecthomas/voluptuous#483]
# CONTRIBUTIONS ONLY

**What does this mean?** I do not have time to fix issues myself. The only way fixes or new features will be added is by people submitting PRs.

**Current status.** Voluptuous is largely feature stable. There hasn't been a need to add new features in a while, but there are some bugs that should be fixed.

**Why?** I no longer use Voluptuous personally (in fact I no longer regularly write Python code). Rather than leave the project in a limbo of people filing issues and wondering why they're note being worked on, I believe this notice will more clearly set expectations.

**Comment by spacegaier** [comment]
What is the context for this issue? You just copy and pasted part of the readme. Please elaborate (the title by itself is not helpful).

**Comment by aleksandr-kotlyar** [comment]
@Aryavui Just install as usual. For example `pip install voluptuous`.
