### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by KapJI** [alecthomas/voluptuous#485]
@alecthomas  @spacegaier Can you please make a new release?

Specifically https://github.com/alecthomas/voluptuous/pull/475 should be useful to enable type checks in projects which use voluptuous.

**Comment by spacegaier** [comment]
I will create one soon

**Comment by spacegaier** [comment]
New release is created and published

https://github.com/alecthomas/voluptuous/releases/tag/0.14.0

https://pypi.org/project/voluptuous/0.14.0/
