### ISSUE TITLE
`from __future__ import annotations` requires python 3.7

### ISSUE THREAD

**Issue by remi-delmas-3000** [alecthomas/voluptuous#490]
Hi just posting this here so that other users like me are aware of the issue: release `0.14.0` introduced the use of type annotations `from __future__ import annotations`, which actually require python >= 3.7 to work as mentioned here https://peps.python.org/pep-0563/.

Voluptuous still advertises python 3.6 and lower as supported.

**Comment by alecthomas** [comment]
Where does it advertise this so we can change it?

**Comment by spacegaier** [comment]
We are indeed still listing 2.7 and 3.6 on pypi (from here https://github.com/alecthomas/voluptuous/blob/master/setup.py).

**Comment by alecthomas** [comment]
Ah I see. It'd be nice if we could somehow keep that in sync with the [CI test matrix](https://github.com/alecthomas/voluptuous/blob/82e87df58c6e301b70838c01267234413cc0f7d5/.github/workflows/tests.yml#L16-L22) and the [tox.ini](https://github.com/alecthomas/voluptuous/blob/master/tox.ini#L2)

**Comment by spacegaier** [comment]
> Ah I see. It'd be nice if we could somehow keep that in sync with the [CI test matrix](https://github.com/alecthomas/voluptuous/blob/82e87df58c6e301b70838c01267234413cc0f7d5/.github/workflows/tests.yml#L16-L22) and the [tox.ini](https://github.com/alecthomas/voluptuous/blob/master/tox.ini#L2)

Not sure if it is worth the hassle to try to set that up, but if someone already knows how to, let me know or provide a PR that handles it.

Closing this issue as resolved via https://github.com/alecthomas/voluptuous/pull/494.
