### ISSUE TITLE
Does Voluptuous support conditional validation?

### ISSUE THREAD

**Issue by jturmel** [alecthomas/voluptuous#56]
Really two main cases, for example:

1) Lets say we have a token that is part of the schema, and the first thing we want to do is validate that the token is a valid hex value and then validate it's a token we actually know about in our datastore that is still valid, but we only want to do the second one (which requires a DB look up if it's even a valid looking token (hex))

2) Validation requires two pieces of the schema to perform proper validation, for example a user is retrieving a list of comments for a feed item and the schema payload requires the user_id (which would be the authenticating user in this case) as well as the feed item_id, both will need to be used in the datastore query to see if they have read permission, so we'd need them both in a single callback.

**Comment by kleins05** [comment]
It is an old thread, but in case someone finds it and since I saw the same question elsewhere...

Yes, in fact, the second case is possible, too! The solution I use is to simply subclass Schema. For the example given above:

```
class CommentRequestSchema(Schema):
    def __call__(self, data):
        data = super().__call__(data)
        if not permission_granted(data['user_id'], data['item_id']):
            raise Invalid('user has no permission')
        return data

s = CommentRequestSchema({
    'user_id': int,
    'feed_id': int
})
s({'user_id': 1, 'feed_id': 1})
````

Or for the example in https://stackoverflow.com/questions/24222304/are-there-any-conditional-rules-for-voluptuous:

````
class MovieSchema(Schema):
    def __call__(self, data):
        data = super().__call__(data)

        bitrates = {
            '1280x720': [10, 8, 6, 4],
            '1920x1080': [20, 16, 12, 8]
        }
        if not data['bitrate'] in bitrates[data['resolution']]:
            raise Invalid('bitrate not supported for this resolution', path=['bitrate'])
        return data

s = MovieSchema({
    'resolution': All(str, Any('1920x1080', '1280x720')),
    'bitrate': int,
})
````

Of course, you can also normalise data in your subclass, if needed. And your subclass can be nested as usual:
````
s = Schema({
    'request': CommentRequestSchema({
        'user_id': int,
        'feed_id': int
    })
})
````

And if you like, you can extend the Schema class of voluptuous to avoid subclassing:
````
class Context:
    pass


class MySchema(Schema):

    def __init__(self, schema, required=False, extra=PREVENT_EXTRA):
        if Context in schema:
            self.context = schema[Context]
            del schema[Context]

        super().__init__(schema, required, extra)

    def __call__(self, v):
        s = super().__call__(v)

        if hasattr(self, 'context'):
            s = self.context(s)

        return s


def comment_request(data):
    if not permission_granted(data['user_id'], data['item_id']):
        raise Invalid('user has no permission')
    return data


s = Schema({
    Context: comment_request,
    'user_id': int,
    'feed_id': int
})
````
