### ISSUE TITLE
voluptuous.SchemaError: unsupported schema data type 'bool'

### ISSUE THREAD

**Issue by xsleonard** [alecthomas/voluptuous#75]
```python
import voluptuous

voluptuous.Schema(bool)  # ok
voluptuous.Schema(False)  # not ok
```

Is there a reason `True` and `False` literals aren't handled?  If not I'll send a patch.

It also looks like `bool` is being handled as a callable and not as a type.  I'm not sure if this was intended.

**Comment by jfindlay** [comment]
Why must a boolean value need to be wrapped in an explicit `Literal()`, unlike [other literals](https://github.com/alecthomas/voluptuous#literals)?  I am not trying to criticize this situation, I am only trying to better understand the library.
