### ISSUE TITLE
Package restructure

### ISSUE THREAD

**Issue by ngmiller** [alecthomas/voluptuous#84]
I've been considering a restructure of the package layout. I propose that the markers, validators, and schema definition objects are separated into corresponding modules.

*Note: This is intended to just get a rough idea of what a potential package layout could look like. I purposely did not copy over all potential declarations for a specific module.*

### `voluptuous.schema`

Contains the top level objects needed to initialize schema definitions and the exceptions/error handling as a result of the validation process.
```
class Undefined(object):
UNDEFINED = Undefined()

class Error(Exception):
class SchemaError(Error):
class Invalid(Error):
class MultipleInvalid(Invalid):
class Schema(object):

def _compile_scalar(schema):
def _iterate_mapping_candidates(schema):
def _iterate_object(obj):

class Object(dict):

etc...
```

### `voluptuous.markers`

```
class Marker(object):

class Required(Marker):
class Optional(Marker):
class Exclusive(Optional):
class Inclusive(Optional):

etc...
```

### `voluptuous.validators`

```
def Any(*validators, **kwargs):
def All(*validators, **kwargs):
def Boolean(v):
def Length(min=None, max=Mone, msg=None):

etc...
```

### `voluptuous.util`

Kind of a catch-all for now, may not be necessary at first.
```
@contextmanager
def raises(exc, msg=None):
```

### Why?

1. Future maintainance and additions will be easier.
2. Less potential for merge conflicts.
3. Modules are neat.

### Backwards compatibility
Introducing a package restructure would certainly break current usage. To mitigate this, perhaps `voluptuous/__init__.py` could contain aliases to all the currently available declarations.

```
from voluptuous import markers
from voluptuous import validators
...
Required = markers.Required
Optional = markers.Optional
...
Boolean = validators.Boolean

etc...
```

(I'm hoping) that could be a fix. If that doesn't work or is undesired for some reason, it may be a deal-breaker on the restructure.

Would you be open to a PR of this nature? I'd appreciate your thoughts. Thanks!

**Comment by tusharmakkar08** [comment]
Should we close this issue now since the restructuring is done?

**Comment by ngmiller** [comment]
@tusharmakkar08 Yep, might as well! Thanks for taking this on.

**Comment by alecthomas** [comment]
👍
