### ISSUE TITLE
Naming the data root

### ISSUE THREAD

**Issue by kolypto** [alecthomas/voluptuous#85]
Since validation errors are often sent to the user, it's annoying to see errors like

    expected int for dictionary value @ data['a']

"data"? What the hell is that? :)

I suggest to add an argument, `data_name` to `Schema.__call__` so we can use it like this:

```python
Schema({'a': int})({'a': None}, data_name="user")
```

and so the error renders to:

    expected int for dictionary value @ user['a']

---

This is disputable, since it's easy to just render a different error message like this:

```python
try:
    schema(data)
except Invalid as e:
    raise RuntimeError('{msg} @ {name}{path}'.format(
        msg=e.message, 
        name='user', 
        path=e.path))
```

What do you think?

**Comment by alecthomas** [comment]
I don't think this is necessary, I now think that formatting the exception manually is a better option, perhaps with a user-defined context manager.
