### ISSUE TITLE
Have the option to drop extra keys

### ISSUE THREAD

**Issue by osiloke** [alecthomas/voluptuous#90]
Hi there,
In a special case where you want to accept only a subset of the json data, it would be nice to drop those extra keys not needed.

**Comment by hoxu** [comment]
Isn't this already possible with `extra=REMOVE_EXTRA` parameter to `Schema`?

https://github.com/alecthomas/voluptuous/blob/d5a7e27dace1fb13194a239dfe84be25fc18bcb1/voluptuous.py#L142-L145

Commit 80c9f2c4b4205ea8f0417f17066b0b8e172f9516
