### ISSUE TITLE
Coerce for Decimal Doesn't Catch decimal.InvalidOperation

### ISSUE THREAD

**Issue by razor-1** [alecthomas/voluptuous#94]
```python
from voluptuous import *
from decimal import *

schema = Schema(Coerce(Decimal))
try:
	schema('t')
except MultipleInvalid as e:
	print "exception MultipleInvalid: " + str(e)
```
------------------
This will output decimal.InvalidOperation: Invalid literal for Decimal: 't'.  voluptuous only catches ValueError and TypeError in Coerce.  Maybe it needs to catch InvalidOperation as well?

**Comment by alecthomas** [comment]
I don't think it would be a good idea to catch `InvalidOperation`. Pretty irritating that it doesn't throw ValueError.
